<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="karstenw.20230817121629.2" a="E"><vh>src</vh>
<v t="karstenw.20230817183046.1" a="E"><vh>@clean brand.py</vh>
<v t="karstenw.20230817183101.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817183101.2"><vh>main</vh></v>
</v>
<v t="karstenw.20230817121654.1"><vh>engine</vh>
<v t="karstenw.20230817121734.1" a="E"><vh>@clean src/engine/__init__.py</vh>
<v t="karstenw.20230817121911.1"><vh>Declarations</vh></v>
</v>
<v t="karstenw.20230817121755.1" a="E"><vh>@clean src/engine/camera.py</vh>
<v t="karstenw.20230817121914.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121914.2"><vh>class Screen</vh>
<v t="karstenw.20230817121914.3"><vh>__init__</vh></v>
<v t="karstenw.20230817121914.4"><vh>get position</vh></v>
<v t="karstenw.20230817121914.5"><vh>set position</vh></v>
<v t="karstenw.20230817121914.6"><vh>get extent</vh></v>
<v t="karstenw.20230817121914.7"><vh>set extent</vh></v>
<v t="karstenw.20230817121914.8"><vh>get resolution</vh></v>
<v t="karstenw.20230817121914.9"><vh>set resolution</vh></v>
<v t="karstenw.20230817121914.10"><vh>get u</vh></v>
<v t="karstenw.20230817121914.11"><vh>set u</vh></v>
<v t="karstenw.20230817121914.12"><vh>get v</vh></v>
<v t="karstenw.20230817121914.13"><vh>set v</vh></v>
<v t="karstenw.20230817121914.14"><vh>get w</vh></v>
<v t="karstenw.20230817121914.15"><vh>set w</vh></v>
<v t="karstenw.20230817121914.16"><vh>width</vh></v>
<v t="karstenw.20230817121914.17"><vh>height</vh></v>
<v t="karstenw.20230817121914.18"><vh>distance</vh></v>
<v t="karstenw.20230817121914.19"><vh>xres</vh></v>
<v t="karstenw.20230817121914.20"><vh>yres</vh></v>
</v>
<v t="karstenw.20230817121914.21"><vh>class Camera</vh>
<v t="karstenw.20230817121914.22"><vh>__init__</vh></v>
<v t="karstenw.20230817121914.23"><vh>position</vh></v>
<v t="karstenw.20230817121914.24"><vh>set position</vh></v>
<v t="karstenw.20230817121914.25"><vh>orientation</vh></v>
<v t="karstenw.20230817121914.26"><vh>set orientation</vh></v>
<v t="karstenw.20230817121914.27"><vh>screen</vh></v>
<v t="karstenw.20230817121914.28"><vh>set screen</vh></v>
<v t="karstenw.20230817121914.29"><vh>distance</vh></v>
<v t="karstenw.20230817121914.30"><vh>get x</vh></v>
<v t="karstenw.20230817121914.31"><vh>set x</vh></v>
<v t="karstenw.20230817121914.32"><vh>get y</vh></v>
<v t="karstenw.20230817121914.33"><vh>set y</vh></v>
<v t="karstenw.20230817121914.34"><vh>get z</vh></v>
<v t="karstenw.20230817121914.35"><vh>set z</vh></v>
<v t="karstenw.20230817121914.36"><vh>get u</vh></v>
<v t="karstenw.20230817121914.37"><vh>set u</vh></v>
<v t="karstenw.20230817121914.38"><vh>get v</vh></v>
<v t="karstenw.20230817121914.39"><vh>set v</vh></v>
<v t="karstenw.20230817121914.40"><vh>get w</vh></v>
<v t="karstenw.20230817121914.41"><vh>set w</vh></v>
<v t="karstenw.20230817121914.42"><vh>get_screen_coordinates</vh></v>
<v t="karstenw.20230817121914.43"><vh>look_at_point</vh></v>
<v t="karstenw.20230817121914.44"><vh>get_azimuth</vh></v>
<v t="karstenw.20230817121914.45"><vh>get_elevation</vh></v>
<v t="karstenw.20230817121914.46"><vh>get_roll</vh></v>
<v t="karstenw.20230817121914.47"><vh>set_roll</vh></v>
</v>
</v>
<v t="karstenw.20230817121756.1"><vh>@clean src/engine/mapper.py</vh>
<v t="karstenw.20230817121932.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121932.2"><vh>class Map</vh>
<v t="karstenw.20230817121932.3"><vh>__init__</vh></v>
<v t="karstenw.20230817121932.4"><vh>sealevel</vh></v>
<v t="karstenw.20230817121932.5"><vh>shape</vh></v>
<v t="karstenw.20230817121932.6"><vh>flat_sea</vh></v>
<v t="karstenw.20230817121932.7"><vh>raw_map</vh></v>
<v t="karstenw.20230817121932.8"><vh>slice</vh></v>
<v t="karstenw.20230817121932.9"><vh>patches_slice</vh></v>
<v t="karstenw.20230817121932.10"><vh>map_positions_slice</vh></v>
<v t="karstenw.20230817121932.11"><vh>patch_positions_slice</vh></v>
<v t="karstenw.20230817121932.12"><vh>normals_slice</vh></v>
<v t="karstenw.20230817121932.13"><vh>colours_slice</vh></v>
<v t="karstenw.20230817121932.14"><vh>patches_list</vh></v>
<v t="karstenw.20230817121932.15"><vh>map_positions_list</vh></v>
<v t="karstenw.20230817121932.16"><vh>patch_positions_list</vh></v>
<v t="karstenw.20230817121932.17"><vh>normals_list</vh></v>
<v t="karstenw.20230817121932.18"><vh>colours_list</vh></v>
<v t="karstenw.20230817121932.19"><vh>patches</vh></v>
<v t="karstenw.20230817121932.20"><vh>map_positions</vh></v>
<v t="karstenw.20230817121932.21"><vh>patch_positions</vh></v>
<v t="karstenw.20230817121932.22"><vh>normals</vh></v>
<v t="karstenw.20230817121932.23"><vh>colours</vh></v>
<v t="karstenw.20230817121932.24"><vh>fix_view</vh></v>
<v t="karstenw.20230817121932.25"><vh>positions_in_view</vh></v>
<v t="karstenw.20230817121932.26"><vh>_make_patches</vh></v>
<v t="karstenw.20230817121932.27"><vh>_colourise</vh></v>
<v t="karstenw.20230817121932.28"><vh>_calc_positions</vh></v>
<v t="karstenw.20230817121932.29"><vh>_calc_normals</vh></v>
<v t="karstenw.20230817121932.30"><vh>_flood</vh></v>
<v t="karstenw.20230817121932.31"><vh>reflood</vh></v>
</v>
<v t="karstenw.20230817121932.32"><vh>class TriMap</vh>
<v t="karstenw.20230817121932.33"><vh>__init__</vh></v>
<v t="karstenw.20230817121932.34"><vh>sealevel</vh></v>
<v t="karstenw.20230817121932.35"><vh>shape</vh></v>
<v t="karstenw.20230817121932.36"><vh>flat_sea</vh></v>
<v t="karstenw.20230817121932.37"><vh>raw_map</vh></v>
<v t="karstenw.20230817121932.38"><vh>slice</vh></v>
<v t="karstenw.20230817121932.39"><vh>patches_slice</vh></v>
<v t="karstenw.20230817121932.40"><vh>patch_positions_slice</vh></v>
<v t="karstenw.20230817121932.41"><vh>map_positions_slice</vh></v>
<v t="karstenw.20230817121932.42"><vh>normals_slice</vh></v>
<v t="karstenw.20230817121932.43"><vh>colours_slice</vh></v>
<v t="karstenw.20230817121932.44"><vh>patches_list</vh></v>
<v t="karstenw.20230817121932.45"><vh>map_positions_list</vh></v>
<v t="karstenw.20230817121932.46"><vh>patch_positions_list</vh></v>
<v t="karstenw.20230817121932.47"><vh>normals_list</vh></v>
<v t="karstenw.20230817121932.48"><vh>colours_list</vh></v>
<v t="karstenw.20230817121932.49"><vh>patches</vh></v>
<v t="karstenw.20230817121932.50"><vh>map_positions</vh></v>
<v t="karstenw.20230817121932.51"><vh>patch_positions</vh></v>
<v t="karstenw.20230817121932.52"><vh>normals</vh></v>
<v t="karstenw.20230817121932.53"><vh>colours</vh></v>
<v t="karstenw.20230817121932.54"><vh>_make_patches</vh></v>
<v t="karstenw.20230817121932.55"><vh>_colourise</vh></v>
<v t="karstenw.20230817121932.56"><vh>_calc_positions</vh></v>
<v t="karstenw.20230817121932.57"><vh>_calc_normals</vh></v>
<v t="karstenw.20230817121932.58"><vh>_flood</vh></v>
<v t="karstenw.20230817121932.59"><vh>reflood</vh></v>
</v>
</v>
<v t="karstenw.20230817121756.2" a="E"><vh>@clean src/engine/mobs.py</vh>
<v t="karstenw.20230817121937.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121937.2" a="E"><vh>class Movable</vh>
<v t="karstenw.20230817121937.3"><vh>__init__</vh></v>
<v t="karstenw.20230817121937.4"><vh>model</vh></v>
<v t="karstenw.20230817121937.6"><vh>position</vh></v>
<v t="karstenw.20230817121937.8"><vh>yaw</vh></v>
<v t="karstenw.20230817121937.10"><vh>pitch</vh></v>
<v t="karstenw.20230817121937.12"><vh>roll</vh></v>
<v t="karstenw.20230817121937.13"><vh>bounding_box</vh></v>
<v t="karstenw.20230817121937.15"><vh>velocity</vh></v>
<v t="karstenw.20230817121937.17"><vh>acceleration</vh></v>
<v t="karstenw.20230817121937.19"><vh>inertia</vh></v>
<v t="karstenw.20230817121937.20"><vh>gravity</vh></v>
<v t="karstenw.20230817121937.23"><vh>friction</vh></v>
<v t="karstenw.20230817121937.24"><vh>move</vh></v>
<v t="karstenw.20230817121937.25"><vh>apply_forces</vh></v>
<v t="karstenw.20230817121937.26"><vh>bounce</vh></v>
<v t="karstenw.20230817121937.27"><vh>impose_boundary_conditions</vh></v>
</v>
<v t="karstenw.20230817121937.28"><vh>class Player</vh>
<v t="karstenw.20230817121937.29"><vh>__init__</vh></v>
<v t="karstenw.20230817121937.30"><vh>fuel</vh></v>
<v t="karstenw.20230817121937.33"><vh>health</vh></v>
<v t="karstenw.20230817121937.35"><vh>rockets</vh></v>
<v t="karstenw.20230817121937.37"><vh>bombs</vh></v>
<v t="karstenw.20230817121937.39"><vh>thrust</vh></v>
<v t="karstenw.20230817121937.41"><vh>rocket</vh></v>
<v t="karstenw.20230817121937.43"><vh>fire</vh></v>
<v t="karstenw.20230817121937.44"><vh>bomb</vh></v>
<v t="karstenw.20230817121937.46"><vh>cool_down</vh></v>
<v t="karstenw.20230817121937.48"><vh>apply_forces</vh></v>
</v>
</v>
<v t="karstenw.20230817121757.1" a="E"><vh>@clean src/engine/particles.py</vh>
<v t="karstenw.20230817121939.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121939.2"><vh>class Particle</vh>
<v t="karstenw.20230817121939.3"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.5"><vh>inertia</vh></v>
<v t="karstenw.20230817121939.7"><vh>gravity</vh></v>
<v t="karstenw.20230817121939.9"><vh>friction</vh></v>
<v t="karstenw.20230817121939.10"><vh>patches</vh></v>
<v t="karstenw.20230817121939.12"><vh>colour</vh></v>
<v t="karstenw.20230817121939.14"><vh>lifetime</vh></v>
<v t="karstenw.20230817121939.16"><vh>elasticity</vh></v>
</v>
<v t="karstenw.20230817121939.17"><vh>class Particles</vh>
<v t="karstenw.20230817121939.18"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.19"><vh>particle</vh></v>
<v t="karstenw.20230817121939.20"><vh>particle</vh></v>
<v t="karstenw.20230817121939.21"><vh>number</vh></v>
<v t="karstenw.20230817121939.22"><vh>visible</vh></v>
<v t="karstenw.20230817121939.23"><vh>visible</vh></v>
<v t="karstenw.20230817121939.24"><vh>positions</vh></v>
<v t="karstenw.20230817121939.25"><vh>positions</vh></v>
<v t="karstenw.20230817121939.26"><vh>patch_positions</vh></v>
<v t="karstenw.20230817121939.27"><vh>patches</vh></v>
<v t="karstenw.20230817121939.28"><vh>velocities</vh></v>
<v t="karstenw.20230817121939.29"><vh>velocities</vh></v>
<v t="karstenw.20230817121939.31"><vh>accelerations</vh></v>
<v t="karstenw.20230817121939.33"><vh>ages</vh></v>
<v t="karstenw.20230817121939.35"><vh>colours</vh></v>
<v t="karstenw.20230817121939.36"><vh>patch_colours</vh></v>
<v t="karstenw.20230817121939.37"><vh>move</vh></v>
<v t="karstenw.20230817121939.38"><vh>apply_forces</vh></v>
<v t="karstenw.20230817121939.39"><vh>bounce</vh></v>
<v t="karstenw.20230817121939.40"><vh>impose_boundary_conditions</vh></v>
<v t="karstenw.20230817121939.41"><vh>add_particle</vh></v>
<v t="karstenw.20230817121939.42"><vh>delete_particle</vh></v>
<v t="karstenw.20230817121939.43"><vh>delete_particles</vh></v>
<v t="karstenw.20230817121939.44"><vh>cull_aged</vh></v>
</v>
<v t="karstenw.20230817121939.45"><vh>class Shots</vh>
<v t="karstenw.20230817121939.46"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.47"><vh>impose_boundary_conditions</vh></v>
<v t="karstenw.20230817121939.48"><vh>cull_aged</vh></v>
</v>
<v t="karstenw.20230817121939.49"><vh>class Shrapnel</vh>
<v t="karstenw.20230817121939.50"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.51"><vh>add_particles</vh></v>
<v t="karstenw.20230817121939.52"><vh>move</vh></v>
</v>
<v t="karstenw.20230817121939.53"><vh>class Exhaust</vh>
<v t="karstenw.20230817121939.54"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.55"><vh>impose_boundary_conditions</vh></v>
<v t="karstenw.20230817121939.56"><vh>add_particle</vh></v>
<v t="karstenw.20230817121939.57"><vh>add_particles</vh></v>
<v t="karstenw.20230817121939.58"><vh>move</vh></v>
</v>
<v t="karstenw.20230817121939.59"><vh>class Stars</vh>
<v t="karstenw.20230817121939.60"><vh>__init__</vh></v>
<v t="karstenw.20230817121939.61"><vh>min_height</vh></v>
<v t="karstenw.20230817121939.62"><vh>min_height</vh></v>
<v t="karstenw.20230817121939.63"><vh>max_height</vh></v>
<v t="karstenw.20230817121939.64"><vh>max_height</vh></v>
<v t="karstenw.20230817121939.65"><vh>add_particles</vh></v>
<v t="karstenw.20230817121939.66"><vh>move</vh></v>
<v t="karstenw.20230817121939.67"><vh>impose_boundary_conditions</vh></v>
<v t="karstenw.20230817121939.68"><vh>impose_boundary_conditions_old</vh></v>
<v t="karstenw.20230817121939.69"><vh>offset</vh></v>
<v t="karstenw.20230817121939.70"><vh>offset</vh></v>
<v t="karstenw.20230817121939.71"><vh>positions</vh></v>
</v>
</v>
<v t="karstenw.20230817121757.2" a="E"><vh>@clean src/engine/shader.py</vh>
<v t="karstenw.20230817121941.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121942.1"><vh>class LightSource</vh>
<v t="karstenw.20230817121942.2"><vh>__init__</vh></v>
<v t="karstenw.20230817121942.3"><vh>position</vh></v>
<v t="karstenw.20230817121942.4"><vh>position</vh></v>
<v t="karstenw.20230817121942.5"><vh>orientation</vh></v>
<v t="karstenw.20230817121942.6"><vh>orientation</vh></v>
<v t="karstenw.20230817121942.7"><vh>distance</vh></v>
<v t="karstenw.20230817121942.8"><vh>distance</vh></v>
<v t="karstenw.20230817121942.9"><vh>x</vh></v>
<v t="karstenw.20230817121942.10"><vh>x</vh></v>
<v t="karstenw.20230817121942.11"><vh>y</vh></v>
<v t="karstenw.20230817121942.12"><vh>y</vh></v>
<v t="karstenw.20230817121942.13"><vh>z</vh></v>
<v t="karstenw.20230817121942.14"><vh>z</vh></v>
<v t="karstenw.20230817121942.15"><vh>u</vh></v>
<v t="karstenw.20230817121942.16"><vh>u</vh></v>
<v t="karstenw.20230817121942.17"><vh>v</vh></v>
<v t="karstenw.20230817121942.18"><vh>v</vh></v>
<v t="karstenw.20230817121942.19"><vh>w</vh></v>
<v t="karstenw.20230817121942.20"><vh>w</vh></v>
</v>
<v t="karstenw.20230817121942.21"><vh>class Shader</vh>
<v t="karstenw.20230817121942.22"><vh>__init__</vh></v>
<v t="karstenw.20230817121942.23"><vh>light_source</vh></v>
<v t="karstenw.20230817121942.24"><vh>light_source</vh></v>
<v t="karstenw.20230817121942.25"><vh>colour</vh></v>
<v t="karstenw.20230817121942.26"><vh>colour</vh></v>
<v t="karstenw.20230817121942.27"><vh>glare</vh></v>
<v t="karstenw.20230817121942.28"><vh>glare</vh></v>
<v t="karstenw.20230817121942.29"><vh>distance_shading</vh></v>
<v t="karstenw.20230817121942.30"><vh>distance_shading</vh></v>
<v t="karstenw.20230817121942.31"><vh>cutoff_distance</vh></v>
<v t="karstenw.20230817121942.32"><vh>cutoff_distance</vh></v>
<v t="karstenw.20230817121942.33"><vh>linear_distance</vh></v>
<v t="karstenw.20230817121942.34"><vh>linear_distance</vh></v>
<v t="karstenw.20230817121942.35"><vh>apply_lighting</vh></v>
</v>
</v>
<v t="karstenw.20230817121758.1" a="E"><vh>@clean src/engine/shadow.py</vh>
<v t="karstenw.20230817121955.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121955.2"><vh>get_shadows</vh></v>
<v t="karstenw.20230817121955.3"><vh>get_small_shadows</vh></v>
</v>
<v t="karstenw.20230817121758.2" a="E"><vh>@clean src/engine/triDobjects.py</vh>
<v t="karstenw.20230817122000.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817122000.2"><vh>class TriD</vh>
<v t="karstenw.20230817122000.3"><vh>__init__</vh></v>
<v t="karstenw.20230817122000.4"><vh>orientation</vh></v>
<v t="karstenw.20230817122000.5"><vh>centre_of_mass</vh></v>
<v t="karstenw.20230817122000.6"><vh>position</vh></v>
<v t="karstenw.20230817122000.7"><vh>position</vh></v>
<v t="karstenw.20230817122000.8"><vh>patches</vh></v>
<v t="karstenw.20230817122000.9"><vh>normals</vh></v>
<v t="karstenw.20230817122000.10"><vh>positions</vh></v>
<v t="karstenw.20230817122000.11"><vh>engine</vh></v>
<v t="karstenw.20230817122000.12"><vh>gun</vh></v>
<v t="karstenw.20230817122000.13"><vh>colours</vh></v>
<v t="karstenw.20230817122000.14"><vh>basecolour</vh></v>
<v t="karstenw.20230817122000.15"><vh>basecolour</vh></v>
<v t="karstenw.20230817122000.16"><vh>yaw</vh></v>
<v t="karstenw.20230817122000.17"><vh>yaw</vh></v>
<v t="karstenw.20230817122000.18"><vh>pitch</vh></v>
<v t="karstenw.20230817122000.19"><vh>pitch</vh></v>
<v t="karstenw.20230817122000.20"><vh>roll</vh></v>
<v t="karstenw.20230817122000.21"><vh>roll</vh></v>
<v t="karstenw.20230817122000.22"><vh>scale</vh></v>
<v t="karstenw.20230817122000.23"><vh>scale</vh></v>
<v t="karstenw.20230817122000.24"><vh>bounding_box</vh></v>
<v t="karstenw.20230817122000.25"><vh>_colourise</vh></v>
<v t="karstenw.20230817122000.26"><vh>_calc_positions</vh></v>
<v t="karstenw.20230817122000.27"><vh>_calc_normals</vh></v>
<v t="karstenw.20230817122000.28"><vh>_apply_rotation</vh></v>
<v t="karstenw.20230817122000.29"><vh>exploding</vh></v>
<v t="karstenw.20230817122000.30"><vh>exploding</vh></v>
<v t="karstenw.20230817122000.31"><vh>exploded</vh></v>
<v t="karstenw.20230817122000.32"><vh>exploded</vh></v>
<v t="karstenw.20230817122000.33"><vh>explode</vh></v>
</v>
<v t="karstenw.20230817122000.34"><vh>class FireFighter</vh>
<v t="karstenw.20230817122000.35"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.36"><vh>class FireFighterStripes</vh>
<v t="karstenw.20230817122000.37"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.38" a="E"><vh>class Pika</vh>
<v t="karstenw.20230817122000.39"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.40" a="E"><vh>class Lander</vh>
<v t="karstenw.20230817122000.41"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.42"><vh>class House</vh>
<v t="karstenw.20230817122000.43"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.44" a="E"><vh>class SimpleHouse</vh>
<v t="karstenw.20230817122000.45"><vh>__init__</vh></v>
</v>
<v t="karstenw.20230817122000.46"><vh>class TriDGroup</vh>
<v t="karstenw.20230817122000.47"><vh>__init__</vh></v>
<v t="karstenw.20230817122000.48"><vh>model</vh></v>
<v t="karstenw.20230817122000.49"><vh>model</vh></v>
<v t="karstenw.20230817122000.50"><vh>number</vh></v>
<v t="karstenw.20230817122000.51"><vh>positions</vh></v>
<v t="karstenw.20230817122000.52"><vh>patches</vh></v>
<v t="karstenw.20230817122000.53"><vh>patch_positions</vh></v>
<v t="karstenw.20230817122000.54"><vh>normals</vh></v>
<v t="karstenw.20230817122000.55"><vh>colours</vh></v>
<v t="karstenw.20230817122000.56"><vh>bboxes</vh></v>
<v t="karstenw.20230817122000.57"><vh>add_object</vh></v>
<v t="karstenw.20230817122000.58"><vh>delete_object</vh></v>
<v t="karstenw.20230817122000.59"><vh>exploding</vh></v>
<v t="karstenw.20230817122000.60"><vh>timeout</vh></v>
<v t="karstenw.20230817122000.61"><vh>explode_object</vh></v>
</v>
</v>
</v>
<v t="karstenw.20230817121704.1" a="E"><vh>@clean src/game.py</vh>
<v t="karstenw.20230817121726.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121726.2" a="E"><vh>class Game</vh>
<v t="karstenw.20230817121726.3" a="E"><vh>__init__</vh>
<v t="karstenw.20230817194702.1"><vh>&lt;&lt; world map &gt;&gt;</vh></v>
<v t="karstenw.20230817194741.1"><vh>&lt;&lt; fonts &gt;&gt;</vh></v>
<v t="karstenw.20230817194824.1"><vh>&lt;&lt; load game objects &gt;&gt;</vh></v>
<v t="karstenw.20230817194901.1"><vh>&lt;&lt; setup camera &gt;&gt;</vh></v>
<v t="karstenw.20230817195031.1"><vh>&lt;&lt; game objects &gt;&gt;</vh></v>
</v>
<v t="karstenw.20230817121726.5"><vh>config</vh></v>
<v t="karstenw.20230817121726.6"><vh>focus_position</vh></v>
<v t="karstenw.20230817121726.7"><vh>_view</vh></v>
<v t="karstenw.20230817121726.8"><vh>update_fixed_camera</vh></v>
<v t="karstenw.20230817121726.9"><vh>update_rear_camera</vh></v>
<v t="karstenw.20230817121726.10"><vh>_populate_world</vh></v>
<v t="karstenw.20230817121726.11"><vh>close_game</vh></v>
<v t="karstenw.20230817121726.12"><vh>return_to_menu</vh></v>
<v t="karstenw.20230817121726.13"><vh>handle_inputs</vh></v>
<v t="karstenw.20230817121726.14"><vh>draw_patches</vh></v>
<v t="karstenw.20230817121726.15"><vh>get_particle_patches</vh></v>
<v t="karstenw.20230817121726.16"><vh>do_step</vh></v>
<v t="karstenw.20230817121727.1"><vh>check_shots_hit</vh></v>
</v>
</v>
<v t="karstenw.20230817121714.1" a="E"><vh>@clean src/menu.py</vh>
<v t="karstenw.20230817121723.1"><vh>Declarations</vh></v>
<v t="karstenw.20230817121723.2" a="E"><vh>class Menu</vh>
<v t="karstenw.20230817121723.3"><vh>__init__</vh></v>
<v t="karstenw.20230817121723.4"><vh>setup</vh></v>
<v t="karstenw.20230817121723.5"><vh>config</vh></v>
<v t="karstenw.20230817121723.6"><vh>items</vh></v>
<v t="karstenw.20230817121723.7"><vh>text</vh></v>
<v t="karstenw.20230817121723.8"><vh>_items</vh></v>
<v t="karstenw.20230817121723.9"><vh>item</vh></v>
<v t="karstenw.20230817121723.10"><vh>resolution</vh></v>
<v t="karstenw.20230817121723.11"><vh>_load_options</vh></v>
<v t="karstenw.20230817121723.12"><vh>_set_options</vh></v>
<v t="karstenw.20230817121723.13"><vh>_save_settings</vh></v>
<v t="karstenw.20230817121723.14"><vh>close</vh></v>
<v t="karstenw.20230817121723.15"><vh>menu_navigation</vh></v>
<v t="karstenw.20230817121723.16"><vh>_relay_input</vh></v>
<v t="karstenw.20230817121723.17"><vh>play_sound</vh></v>
</v>
<v t="karstenw.20230817121723.18"><vh>draw_menu</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="karstenw.20230817121629.2"></t>
<t tx="karstenw.20230817121654.1"></t>
<t tx="karstenw.20230817121704.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121714.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121723.1">
from __future__ import print_function

import json
import pygame
import pygame.locals as l


KEYBOARD = {l.K_UP: 'up', l.K_k: 'up', l.K_w: 'up',
            l.K_DOWN: 'down', l.K_j: 'down', l.K_s: 'down',
            l.K_LEFT: 'left', l.K_h: 'left', l.K_a: 'left',
            l.K_RIGHT: 'right', l.K_l: 'right', l.K_d: 'right',
            l.K_RETURN: 'start', l.K_SPACE: 'start',
            l.K_ESCAPE: 'quit', l.K_F1: 'help', l.K_TAB: 'pause'}


</t>
<t tx="karstenw.20230817121723.10">@property
def resolution(self):
    return tuple(self.options["resolution"])

</t>
<t tx="karstenw.20230817121723.11">def _load_options(self, filename):
    try:
        with open(filename, 'r') as f:
            self.options = json.load(f)
    except IOError:
        print( "Loading default settings..." )
        with open(self._default, 'r') as f:
            self.options = json.load(f)

    self._set_options()

</t>
<t tx="karstenw.20230817121723.12">def _set_options(self):

    for o in self.options.keys():

        for n, item in enumerate(self._structure["options"]["items"]):

            if item[0] == o:

                break

        if self._structure["options"]["items"][n][1][0] in ("toggle",
                                                            "lander"):

            self._structure["options"]["items"][n][1][1] = int(
                self.options[o])

        elif self._structure["options"]["items"][n][1][0] == "list":

            for m, l in enumerate(self._structure["options"
                                                  ]["items"][n][1][2]):
                if l == self.options[o]:

                    self._structure["options"]["items"][n][1][1] = m

</t>
<t tx="karstenw.20230817121723.13">def _save_settings(self):

    for o in self.options.keys():

        for n, item in enumerate(self._structure["options"]["items"]):

            if item[0] == o:

                break

        if self._structure["options"]["items"][n][1][0] in ("toggle",
                                                            "lander"):

            self.options[o] = (1 == self._structure["options"
                                                    ]["items"][n][1][1])

        elif self._structure["options"]["items"][n][1][0] == "list":

            self.options[o] = self._structure["options"]["items"][n][1][2][
                self._structure["options"]["items"][n][1][1]]

        else:
            print( o )

    with open(self._config, 'w') as f:
        json.dump(self.options, f)

</t>
<t tx="karstenw.20230817121723.14">def close(self):
    """ Close menu. """

    self._save_settings()

    return "quit"

</t>
<t tx="karstenw.20230817121723.15">def menu_navigation(self):
    """ Handles inputs from user. """
    flag = "menu"

    for event in pygame.event.get():

        if event.type == l.QUIT:

            flag = self.close()

        elif event.type == l.KEYDOWN and event.key in KEYBOARD.keys():

            if KEYBOARD[event.key] == 'quit':

                self.menu = "main menu"
                self._item = 0

            elif KEYBOARD[event.key] == 'up':

                self._item = (self._item - 1) % self._items

            elif KEYBOARD[event.key] == 'down':

                self._item = (self._item + 1) % self._items

            elif KEYBOARD[event.key] == 'help':

                flag = "help"
                self._item = 0

            elif KEYBOARD[event.key] == 'pause':

                pygame.mouse.set_visible(True)

            else:
                self.play_sound()
                flag = self._relay_input(event.key)

        elif event.type == l.MOUSEBUTTONDOWN:

            pygame.mouse.set_visible(False)

    return flag

</t>
<t tx="karstenw.20230817121723.16">def _relay_input(self, event_key):

    if KEYBOARD[event_key] == 'start':

        if self.item[1][0] == 'start':

            return "game"

        elif self.item[1][0] == 'quit':

            return "quit"

        elif self.item[1][0] == 'hiscore':

            return "hiscore"

        elif self.item[1][0] == 'gallery':

            return "gallery"

        elif self.item[1][0] == 'credits':

            return "credits"

        elif self.item[1][0] == 'menu':

            self.menu = self.item[1][1]
            self._item = 0

        elif self.item[1][0] == "toggle":

            self.item[1][1] = (self.item[1][1] + 1) % 2

        elif self.item[1][0] == "list":

            self.item[1][1] = ((self.item[1][1] + 1) %
                               len(self.item[1][2]))

        elif self.item[1][0] == "default":

            self._load_options(self._default)

    elif KEYBOARD[event_key] == 'left':

        if self.item[1][0] in ("toggle", "lander"):

            self.item[1][1] = (self.item[1][1] - 1) % 2

        elif self.item[1][0] == "list":

            self.item[1][1] = ((self.item[1][1] - 1) %
                               len(self.item[1][2]))

    elif KEYBOARD[event_key] == 'right':

        if self.item[1][0] == "toggle":

            self.item[1][1] = (self.item[1][1] + 1) % 2

        elif self.item[1][0] == "list":

            self.item[1][1] = ((self.item[1][1] + 1) %
                               len(self.item[1][2]))

    self._save_settings()

    return "menu"

</t>
<t tx="karstenw.20230817121723.17">def play_sound(self):
    if self._menu_sound:
        self._menu_sound.play()

</t>
<t tx="karstenw.20230817121723.18">def draw_menu(menu, surface):
    centre = menu.setup["centre"]
    resolution = menu.options["resolution"]
    fontsize = int( menu.setup["fontsize"] * resolution[0] / 320 )
    font = pygame.font.Font(menu.setup["font"], fontsize)

    surface.fill((0, 0, 0))

    for n, i in enumerate(menu.text):

        colour = menu.setup["colour"]

        text = font.render("  {0}  ".format(i[0]), True, colour)

        if centre:

            textpos = text.get_rect(center=(resolution[0] / 2,
                                            (2 + n) * (fontsize + 1)))

        else:

            textpos = text.get_rect(centery=(2 + n) * (fontsize + 1))

        surface.blit(text, textpos)

    for n, i in enumerate(menu.items):

        if i == menu.item:

            colour = menu.setup["selected"]

        else:

            colour = menu.setup["colour"]

        if i[1][0] == "toggle":

            text = font.render("  {0}: {1}  ".format(i[0], i[1][2][i[1][1]]),
                               True, colour)

        if i[1][0] == "list":

            text = font.render("  {0}: {1}  ".format(i[0], i[1][3][i[1][1]]),
                               True, colour)

        else:

            text = font.render("  {0}  ".format(i[0]), True, colour)

        if centre:

            textpos = text.get_rect(center=(resolution[0] / 2, resolution[1] -
                                            (1 + fontsize) *
                                            (len(menu.items) - n + 1)))

        else:

            textpos = text.get_rect(centery=resolution[1] -
                                    (1 + fontsize) * (len(menu.items) - n + 1))

        surface.blit(text, textpos)
</t>
<t tx="karstenw.20230817121723.2">class Menu(object):
    """
    A simple menu class, configured using JSON.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121723.3">def __init__(self, _structure='menu.conf', options='user.conf',
             default='default.conf', mixer=None):
    self._item = 0
    self.menu = "main menu"

    with open(_structure, 'r') as f:
        self._structure = json.load(f)

    self._default = default
    self._config = options

    self._load_options(options)

    if mixer is not None:
        try:
            self._menu_sound = mixer.Sound(self.setup.get("sound"))
        except (pygame.error, IOError):
            self._menu_sound = None
    else:
        self._menu_sound = None

    pygame.mouse.set_visible(False)

</t>
<t tx="karstenw.20230817121723.4">@property
def setup(self):
    return self._structure["setup"]

</t>
<t tx="karstenw.20230817121723.5">@property
def config(self):
    return self.options

</t>
<t tx="karstenw.20230817121723.6">@property
def items(self):
    return self._structure[self.menu]['items']

</t>
<t tx="karstenw.20230817121723.7">@property
def text(self):
    return self._structure[self.menu]['text']

</t>
<t tx="karstenw.20230817121723.8">@property
def _items(self):
    return len(self.items)

</t>
<t tx="karstenw.20230817121723.9">@property
def item(self):
    return self._structure[self.menu]["items"][self._item]

</t>
<t tx="karstenw.20230817121726.1">

from __future__ import print_function

import datetime as dt
import numpy as np
import pygame
from pygame import locals as l
from . import engine as e

KEYBOARD = {l.K_UP: 'up', l.K_k: 'up', l.K_w: 'up',
            l.K_DOWN: 'down', l.K_j: 'down', l.K_s: 'down',
            l.K_LEFT: 'left', l.K_h: 'left', l.K_a: 'left',
            l.K_RIGHT: 'right', l.K_l: 'right', l.K_d: 'right',
            l.K_RETURN: 'start', l.K_SPACE: 'start',
            l.K_ESCAPE: 'quit', l.K_F1: 'help', l.K_TAB: 'pause'
            }


</t>
<t tx="karstenw.20230817121726.10">def _populate_world(self):
    n_houses = 42
    settlements = e.triDobjects.TriDGroup(
        model=e.triDobjects.House(scale=0.618),
        timeout=0.5,
    )
    angles = 2 * np.pi * np.random.random(n_houses)
    candidates = self.world.map_positions.copy()

    for n in range(n_houses):
        x, y = (np.random.random(2) * self.world.shape).astype(int)
        X, Y = np.mgrid[x - 1: x + 2, y - 1: y + 2]
        X %= self.world.shape[self.X]
        Y %= self.world.shape[self.Y]

        while((candidates[X, Y, self.Z] &lt;= 0).any()):
            x, y = (np.random.random(2) * self.world.shape).astype(int)
            X, Y = np.mgrid[x - 1: x + 2, y - 1: y + 2]
            X %= self.world.shape[self.X]
            Y %= self.world.shape[self.Y]

        settlements.add_object(
            position=np.array([x, y, candidates[x, y, self.Z]]),
            yaw=angles[n])

        candidates[X, Y, self.Z] *= 0

    self.houses = settlements

</t>
<t tx="karstenw.20230817121726.11">def close_game(self):
    """ Close game. """

    pygame.event.set_grab(False)

    return "quit"

</t>
<t tx="karstenw.20230817121726.12">def return_to_menu(self):
    """ Close game. """

    self.player.velocity *= 0.0
    return "menu"

</t>
<t tx="karstenw.20230817121726.13">def handle_inputs(self):
    """ Handles inputs from user. """
    flag = "game"

    for event in pygame.event.get():

        if event.type == l.QUIT:

            flag = self.close_game()

        elif event.type == l.KEYDOWN and event.key in KEYBOARD.keys():

            if KEYBOARD[event.key] == 'quit':

                flag = self.return_to_menu()

            elif KEYBOARD[event.key] == 'left':

                self.player.yaw = ((self.player.yaw + np.pi / 24) %
                                   (2 * np.pi))

            elif KEYBOARD[event.key] == 'right':

                self.player.yaw = ((self.player.yaw - np.pi / 24) %
                                   (2 * np.pi))

            elif KEYBOARD[event.key] == 'up':

                self.player.pitch = min(self.player.pitch + np.pi / 24,
                                        np.pi * 0.5)

            elif KEYBOARD[event.key] == 'down':

                self.player.pitch = max(self.player.pitch - np.pi / 24,
                                        -np.pi * 0.5)

            elif KEYBOARD[event.key] == 'pause':

                self._pause = not self._pause

                pygame.event.set_grab(not self._pause)

                pygame.mouse.set_visible(self._pause)

                pygame.mouse.get_rel()

            else:

                pass
                # flag = self._relay_input(event.key)

        elif event.type == l.MOUSEMOTION and pygame.event.get_grab():

            motion = np.array(pygame.mouse.get_rel())

            self.player.yaw = (self.player.yaw - motion[self.X] *
                               self._sensitivity) % (2 * np.pi)

            self.player.pitch = (self.player.pitch - motion[self.Y] *
                                 self._sensitivity)

            if self.player.pitch &lt; -2.0 * np.pi / 3.0:

                self.player.pitch = -2.0 * np.pi / 3.0

            elif self.player.pitch &gt; 3.0 * np.pi / 4.0:

                self.player.pitch = 3.0 * np.pi / 4.0

        elif event.type == l.MOUSEBUTTONDOWN:

            if pygame.event.get_grab():

                if event.button == 1:

                    self.player.fire = True

                elif event.button == 2:

                    self.player.rocket = True

                elif event.button == 3:

                    self.player.thrust = True

            else:

                pygame.event.set_grab(True)

                pygame.mouse.set_visible(False)

                pygame.mouse.get_rel()

        elif event.type == l.MOUSEBUTTONUP:

            if event.button == 1:

                self.player.fire = False

            elif event.button == 2:

                self.player.rocket = False

            elif event.button == 3:

                self.player.thrust = False

    return flag

</t>
<t tx="karstenw.20230817121726.14">def draw_patches(self, positions, patches, colours, surface):
    # draw objects and particles:
    order = np.argsort(-((positions - self.camera.position) ** 2).mean(-1))

    for n in order:
        if colours[n, 3]:
            pygame.draw.polygon(surface, colours[n], patches[n])
            pygame.draw.polygon(surface, colours[n], patches[n], 1)

</t>
<t tx="karstenw.20230817121726.15">def get_particle_patches(self, particles, view):
    if particles.number and particles.visible:
        positions = particles.patch_positions.copy()
        positions = self.world.fix_view(self.focus_position, view,
                                        positions)
        in_view = self.world.positions_in_view(self.focus_position, view,
                                               positions)

        if in_view.size:
            positions = positions[in_view]
            patches = self.world.fix_view(
                self.focus_position, view,
                particles.patches[in_view])

            if self.camera.position[self.Z] &lt; self._culling_height:
                shadows, shadow_positions = e.shadow.get_shadows(
                    patches.copy(), self.world)
                shadows, shadow_depths = \
                    self.camera.get_screen_coordinates(shadows)
                shadow_colours = np.array([[0, 0, 0, 1]]) * np.ones(
                    (shadows.shape[0], 1))

            else:
                shadow_positions = np.empty((0, 3))
                shadows = np.empty((0, 4, 2))
                shadow_colours = np.empty((0, 4))

            (patches, depths) = self.camera.get_screen_coordinates(patches)
            colours = particles.patch_colours[in_view]
            colours = self.shader.apply_lighting(positions, positions,
                                                 colours, scatter=False)

        else:
            positions = np.empty((0, 3))
            patches = np.empty((0, 3, 2))
            colours = np.empty((0, 4))

            shadow_positions = np.empty((0, 3))
            shadows = np.empty((0, 4, 2))
            shadow_colours = np.empty((0, 4))

    else:
        positions = np.empty((0, 3))
        patches = np.empty((0, 3, 2))
        colours = np.empty((0, 4))

        shadow_positions = np.empty((0, 3))
        shadows = np.empty((0, 4, 2))
        shadow_colours = np.empty((0, 4))

    return (positions, patches, colours, shadow_positions, shadows,
            shadow_colours)

</t>
<t tx="karstenw.20230817121726.16">def do_step(self, surface):
    flag = self.handle_inputs()

    # get map in view:
    if self.camera.position[self.Z] &lt; self._culling_height:
        map_positions = self.world.patch_positions_list(
            self.focus_position, self._view)
        map_normals = self.world.normals_list(self.focus_position,
                                              self._view)
        map_patches, map_depths = self.camera.get_screen_coordinates(
            self.world.patches_list(self.focus_position, self._view))
        map_colours = self.world.colours_list(self.focus_position,
                                              self._view)
        map_colours = self.shader.apply_lighting(map_positions,
                                                 map_normals,
                                                 map_colours,
                                                 culling=False)
    else:
        map_positions = np.empty((0, 3))
        map_normals = np.empty((0, 3))
        map_patches = np.empty((0, 4, 2))
        map_colours = np.empty((0, 4))

    # explode houses:
    if np.any(self.houses.exploding):
        for ind, t in enumerate(self.houses.exploding):
            if t:
                if (dt.datetime.now() - t &gt; self.houses.timeout):
                    self.houses.delete_object(ind)
                    break
                else:
                    self.houses.explode_object(ind)

    # get objects in view:
    if self.camera.position[self.Z] &lt; self._culling_height:
        view = self._view
        houses_positions = self.houses.positions.copy()
        houses_positions = self.world.fix_view(self.focus_position, view,
                                               houses_positions)
        houses_in_view = self.world.positions_in_view(
            self.focus_position, view, houses_positions)

        if houses_in_view.size:
            houses_positions = self.world.fix_view(
                self.focus_position, view,
                self.houses.patch_positions(houses_in_view))
            houses_patches = self.world.fix_view(
                self.focus_position, view,
                self.houses.patches(houses_in_view))

            (houses_patches, houses_depths) = self.camera.get_screen_coordinates(houses_patches)
            houses_normals = self.houses.normals(houses_in_view)
            houses_colours = self.houses.colours(houses_in_view)
            houses_colours = self.shader.apply_lighting(houses_positions,
                                                        houses_normals,
                                                        houses_colours)

        else:
            houses_positions = np.empty((0, 3))
            houses_patches = np.empty((0, 3, 2))
            houses_colours = np.empty((0, 4))

    else:
        houses_positions = np.empty((0, 3))
        houses_patches = np.empty((0, 3, 2))
        houses_colours = np.empty((0, 4))

    # get player:
    player_positions = self.player.model.positions
    player_normals = self.player.model.normals
    player_patches, player_depth = self.camera.get_screen_coordinates(
        self.player.model.patches)
    player_colours = self.player.model.colours.copy()
    player_colours = self.shader.apply_lighting(player_positions,
                                                player_normals,
                                                player_colours)
    # get shadow:
    if self.camera.position[self.Z] &lt; self._culling_height:
        player_shadow, player_shadow_positions = e.shadow.get_shadows(
            self.player.model.patches.copy(), self.world)
        player_shadow, shadow_depths = self.camera.get_screen_coordinates(
            player_shadow)
        player_shadow_colours = np.array([[0, 0, 0, 1]]) * np.ones(
            (player_shadow.shape[0], 1))
    else:
        player_shadow_positions = np.empty((0, 3))
        player_shadow = np.empty((0, 4, 2))
        player_shadow_colours = np.empty((0, 4))

    # Handle particles:
    if self.player.fire and (self.shots.number == 0 or
                             self.shots.ages[-1] &gt; self.player.cool_down):
        self.shots.add_particle(self.player.model.gun,
                                self.player.model.orientation[self.V] * 16
                                + self.player.velocity, np.zeros(3))

    if self.player.model.exploding:
        if not self.player.model.exploded:
            N = np.random.randint(144, 233)
            self.exhaust.add_particles(
                self.player.position * np.ones((N, 3)),
                (2 * np.random.random((N, 3)) - 1) * 5
                + 0.9 * self.player.velocity * np.ones((N, 3)),
                np.zeros((N, 3)))
            self.player.model.exploded = True
    elif self.player.thrust:
        N = np.random.randint(0, 5)
        self.exhaust.add_particles(
            self.player.model.engine * np.ones((N, 3)),
            (2 * np.random.random((N, 3)) - 1) * 2 *
            self.player.model.orientation[self.U] +
            (2 * np.random.random((N, 3)) - 1) * 2 *
            self.player.model.orientation[self.V] +
            -self.player.model.orientation[self.W] *
            (7 + 2 * np.random.random((N, 3))) +
            self.player.velocity * np.ones((N, 3)), np.zeros((N, 3)))


    if (self.player.position[self.Z] &lt; self.star_field.min_height -
            self.camera.screen.extent[self.V] * 0.5):
        self.star_field.visible = False
    else:
        self.star_field.visible = True

    (shots_positions, shots_patches, shots_colours,
     shots_shadow_positions, shots_shadows, shots_shadow_colours) = \
        self.get_particle_patches(self.shots, self._view +
                                  self.camera.distance - 0.5)

    (exhaust_positions, exhaust_patches, exhaust_colours,
     exhaust_shadow_positions, exhaust_shadows, exhaust_shadow_colours) = \
        self.get_particle_patches(self.exhaust, self._view +
                                  self.camera.distance - 0.5)

    (shrapnel_positions, shrapnel_patches, shrapnel_colours,
     shrapnel_shadow_positions, shrapnel_shadows,
     shrapnel_shadow_colours) = self.get_particle_patches(self.shrapnel,
                                                          self._view)

    (stars_positions, stars_patches, stars_colours,
     stars_shadow_positions, stars_shadows, stars_shadow_colours) = \
        self.get_particle_patches(self.star_field, self._view +
                                  self.camera.distance - 0.5)

    # aggregate draw data:
    object_positions = np.r_[player_positions, shots_positions,
                             exhaust_positions, shrapnel_positions,
                             houses_positions, stars_positions]
    object_patches = list(player_patches[:])
    object_patches.extend(list(shots_patches[:]))
    object_patches.extend(list(exhaust_patches[:]))
    object_patches.extend(list(shrapnel_patches[:]))
    object_patches.extend(list(houses_patches[:]))
    object_patches.extend(list(stars_patches[:]))
    object_colours = np.r_[player_colours, shots_colours, exhaust_colours,
                           shrapnel_colours, houses_colours, stars_colours]

    shadow_positions = np.r_[player_shadow_positions,
                             shots_shadow_positions,
                             exhaust_shadow_positions,
                             shrapnel_shadow_positions]
    shadow_patches = list(player_shadow[:])
    shadow_patches.extend(list(shots_shadows[:]))
    shadow_patches.extend(list(exhaust_shadows[:]))
    shadow_patches.extend(list(shrapnel_shadows[:]))
    shadow_colours = np.r_[player_shadow_colours, shots_shadow_colours,
                           exhaust_shadow_colours, shrapnel_shadow_colours]

    # sort patches:

    # draw:
    surface.fill((0, 0, 0))

    # draw landscape:
    self.draw_patches(map_positions, map_patches, map_colours, surface)

    # draw shadows:
    self.draw_patches(shadow_positions, shadow_patches, shadow_colours,
                      surface)

    # draw objects and particles:
    self.draw_patches(object_positions, object_patches, object_colours,
                      surface)

    if self._pause:

        colour = (204, 153, 153, 153)

        text = self._font.render("press TAB to UNPAUSE", True, colour)

        textpos = text.get_rect(center=(self.config["resolution"][0] / 2,
                                        self.config["resolution"][1] / 2))

        surface.blit(text, textpos)

    elif self._gameover:

        colour = (204, 153, 153, 153)

        text = self._font.render(
            "GAME OVER", True, colour,
        )

        textpos = text.get_rect(
            center=(self.config["resolution"][0] / 2,
                    self.config["resolution"][1] / 3)
        )

        surface.blit(text, textpos)

        text = self._font.render(
            "Points: {}".format(self._points), True, colour,
        )

        textpos = text.get_rect(
            center=(self.config["resolution"][0] / 2,
                    self.config["resolution"][1] / 2)
        )

        surface.blit(text, textpos)

        text = self._font.render(
            "Press ESCAPE to RETURN TO MENU", True, colour,
        )

        textpos = text.get_rect(
            center=(self.config["resolution"][0] / 2,
                    2 * self.config["resolution"][1] / 3)
        )

        surface.blit(text, textpos)

        pygame.event.set_grab(not self._gameover)

        pygame.mouse.set_visible(self._gameover)

        pygame.mouse.get_rel()

    else:

        self.player.move(self._dt)
        self.player.impose_boundary_conditions(self.world)

        if self.shots.number:
            self.shots.move(self._dt)
            self.check_shots_hit()
            shrapnel = self.shots.impose_boundary_conditions(self.world)
            if shrapnel is not None:
                self.shrapnel.add_particles(*shrapnel)

        if self.shrapnel.number:
            self.shrapnel.impose_boundary_conditions(self.world)
            self.shrapnel.move(self._dt)

        if self.exhaust.number:
            shrapnel = self.exhaust.impose_boundary_conditions(self.world)
            self.exhaust.move(self._dt)
            if shrapnel is not None:
                self.shrapnel.add_particles(*shrapnel)

        if self.star_field.number and self.star_field.visible:
            self.star_field.offset = self.player.position
            self.star_field.impose_boundary_conditions()
            self.star_field.move(self.player.velocity *
                                 np.array([1.0, 1.0, 0.0]), self._dt)

        self.update_camera()

    if self.player.model.exploding:
        try:
            self._gameover = (
                self._gameover_timer
                &lt; dt.datetime.now() - dt.timedelta(seconds=1)
            )
        except TypeError:
            self._gameover_timer = dt.datetime.now()

    return flag

</t>
<t tx="karstenw.20230817121726.2">class Game(object):
    """
    Here be docstring.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121726.3">def __init__(self, config, world, font, fontsize, fps):
    pygame.event.set_grab(True)
    pygame.mouse.set_visible(False)

    self._config = config
    self._sensitivity = np.pi / config["control"]
    self._dt = 1.0 / fps

    &lt;&lt; world map &gt;&gt;

    &lt;&lt; fonts &gt;&gt;

    &lt;&lt; load game objects &gt;&gt;

    &lt;&lt; setup camera &gt;&gt;

    &lt;&lt; game objects &gt;&gt;

    self._pause = False
    self._gameover = False
    self._gameover_timer = None
    self._points = 0

    pygame.mouse.get_rel()

    print( "game starting" )

</t>
<t tx="karstenw.20230817121726.5">@property
def config(self):
    return self._config

@config.setter
def config(self, val):
    self._config = val

</t>
<t tx="karstenw.20230817121726.6">@property
def focus_position(self):
    return self.player.position

</t>
<t tx="karstenw.20230817121726.7">@property
def _view(self):
    return self._config["view"]

</t>
<t tx="karstenw.20230817121726.8">def update_fixed_camera(self):
    offset = np.array([0, self._view[self.Y] / 2.0 + 9.0, -0.0])

    self.camera.position = self.focus_position - offset

    self.camera.position[self.Z] = max(self.camera.position[self.Z], 6.0)

    self.light_source.position = self.camera.position + np.array([0, 0, 0])

</t>
<t tx="karstenw.20230817121726.9">def update_rear_camera(self):
    look_at = self.focus_position.copy()
    look_at[self.Z] = max(look_at[self.Z], 6.0)
    offset = self._view[self.Y] / 2.0 + 9.0

    self.camera.position = (look_at - offset *
                            np.array([-np.sin(self.player.model.yaw),
                                       np.cos(self.player.model.yaw),
                                       0.0]))

    self.camera.look_at_point(look_at)

    self.light_source.position = self.camera.position + np.array([0, 0, 0])

</t>
<t tx="karstenw.20230817121727.1">def check_shots_hit(self):
    hits = (((
        self.shots.positions[:, np.newaxis]
        - self.houses.positions[np.newaxis, :]
    ) ** 2).sum(axis=2) &lt; self.houses.model.scale).sum(axis=0)

    for house_index, house_position in enumerate(self.houses.positions):
        if hits[house_index] and not self.houses.exploding[house_index]:
            print( "BOOM!" )
            N = np.random.randint(89, 144)
            offset = np.ones((N, 3))
            offset[:, self.Z] = 0
            self.exhaust.add_particles(
                house_position * np.ones((N, 3)),
                (2 * np.random.random((N, 3)) - offset) * 5,
                np.zeros((N, 3))
            )
            self.houses.explode_object(house_index)
            self._points -= 1
            break
</t>
<t tx="karstenw.20230817121734.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121755.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121756.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121756.2">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121757.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121757.2">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121758.1">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121758.2">@language python
@tabwidth -4
@others
</t>
<t tx="karstenw.20230817121911.1">from . import camera
from . import mapper
from . import mobs
from . import particles
from . import shader
from . import shadow
from . import triDobjects
</t>
<t tx="karstenw.20230817121914.1">import numpy as np


</t>
<t tx="karstenw.20230817121914.10">@property
def u(self):
    return self._position[self.U]

</t>
<t tx="karstenw.20230817121914.11">@u.setter
def u(self, val):
    self._position[self.U] = val

</t>
<t tx="karstenw.20230817121914.12">@property
def v(self):
    return self._position[self.V]

</t>
<t tx="karstenw.20230817121914.13">@v.setter
def v(self, val):
    self._position[self.V] = val

</t>
<t tx="karstenw.20230817121914.14">@property
def w(self):
    return self._position[self.W]

</t>
<t tx="karstenw.20230817121914.15">@w.setter
def w(self, val):
    self._position[self.W] = val

</t>
<t tx="karstenw.20230817121914.16">@property
def width(self):
    return self._extent[self.X]

</t>
<t tx="karstenw.20230817121914.17">@property
def height(self):
    return self._extent[self.Y]

</t>
<t tx="karstenw.20230817121914.18">@property
def distance(self):
    return self._position[self.V]

</t>
<t tx="karstenw.20230817121914.19">@property
def xres(self):
    return self._resolution[self.X]

</t>
<t tx="karstenw.20230817121914.2">class Screen(object):
    """
    A Screen object for use with a Camera object.

    The Screen is described by the following parameters:
    * extent:
        - the Screen's extent (width, height) in spatial units

    * resolution:
        - the Screen's resoultion in pixels (xres, yres)

    * position:
        - position of the centre of the Screen in uvw-space, using the Camera
          position as origin.
          The v component is the proper orthogonal distance to the Screen from
          the Camera.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121914.20">@property
def yres(self):
    return self._resolution[self.Y]


</t>
<t tx="karstenw.20230817121914.21">class Camera(object):
    """
    A simple Camera object.

    The Camera are defined by the following parameters:
    * position:
        - one vector describing the position of the Camera in xyz-space.

    * orientation:
        - a set of three orthogonal unit vectors (u, v, w) analogous to and
          expressed in the (x, y, z) set of unit vectors and using the same
          metric/normalisation.
          Of these, the u and w vectors describe the orientation of the Screen
          relative to the Camera ("roll" and "elevation") and v points
          in the viewing direction.

    * screen:
        - the screen is described by its extent (width, height) in spatial
          units, by its resolution in pixels (xres, yres), and by the position
          of the centre of in uvw-space using the Camera position as
          origin.
          The v component is the proper orthogonal distance to the Screen from
          the Camera.
          See the Screen class for details!

    The Camera has the following methods:
    * get_screen_coordinates(points):
        - returns the screen coordinate of points (an N x 3-array of positions
          in xyz-space) based on current Camera position and orientation.

    * look_at_point(point):
        - turn camera to look at point, keeping position and roll constant.

    * get_azimuthl():
        - returns current azimuthal angle (angle to x-axis) of Camera
          orientation.

    * get_elevation():
        - returns current elevation angle (angle to xy-plane) of Camera
          orientation

    * get_roll():
        - returns current roll angle (rotation around v-axis) of Camera
          orientation.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121914.22">def __init__(self,
             position=np.array([6.0, -9.0, 6.0]),
             orientation=np.array([[1.0, 0.0, 0.0],     # u
                                   [0.0, 1.0, 0.0],     # v
                                   [0.0, 0.0, 1.0]]),   # w
             screen=Screen()):

    self.position = position

    self.orientation = orientation

    self.screen = screen

    self._norms = self.screen.resolution / self.screen.extent

</t>
<t tx="karstenw.20230817121914.23">@property
def position(self):
    return self._position

</t>
<t tx="karstenw.20230817121914.24">@position.setter
def position(self, val):
    self._position = val

</t>
<t tx="karstenw.20230817121914.25">@property
def orientation(self):
    return self._orientation

</t>
<t tx="karstenw.20230817121914.26">@orientation.setter
def orientation(self, val):
    self._orientation = val

</t>
<t tx="karstenw.20230817121914.27">@property
def screen(self):
    return self._screen

</t>
<t tx="karstenw.20230817121914.28">@screen.setter
def screen(self, val):
    self._screen = val

</t>
<t tx="karstenw.20230817121914.29">@property
def distance(self):
    return self.screen.distance

</t>
<t tx="karstenw.20230817121914.3">def __init__(self,
             extent=np.array([12.0, 9.0]), resolution=np.array([320, 240]),
             position=np.array([0.0, 9.0, -1.5])):

    self.position = position

    self.extent = extent

    self.resolution = resolution

</t>
<t tx="karstenw.20230817121914.30">@property
def x(self):
    return self._position[self.X]

</t>
<t tx="karstenw.20230817121914.31">@x.setter
def x(self, val):
    self._position[self.X] = val

</t>
<t tx="karstenw.20230817121914.32">@property
def y(self):
    return self._position[self.Y]

</t>
<t tx="karstenw.20230817121914.33">@y.setter
def y(self, val):
    self._position[self.Y] = val

</t>
<t tx="karstenw.20230817121914.34">@property
def z(self):
    return self._position[self.Z]

</t>
<t tx="karstenw.20230817121914.35">@z.setter
def z(self, val):
    self._position[self.Z] = val

</t>
<t tx="karstenw.20230817121914.36">@property
def u(self):
    return self._orientation[self.U]

</t>
<t tx="karstenw.20230817121914.37">@u.setter
def u(self, val):
    self._orientation[self.U] = val

</t>
<t tx="karstenw.20230817121914.38">@property
def v(self):
    return self._orientation[self.V]

</t>
<t tx="karstenw.20230817121914.39">@v.setter
def v(self, val):
    self._orientation[self.V] = val

</t>
<t tx="karstenw.20230817121914.4">@property
def position(self):
    return self._position

</t>
<t tx="karstenw.20230817121914.40">@property
def w(self):
    return self._orientation[self.W]

</t>
<t tx="karstenw.20230817121914.41">@w.setter
def w(self, val):
    self._orientation[self.W] = val

</t>
<t tx="karstenw.20230817121914.42">def get_screen_coordinates(self, points):
    # Perform projections:
    # projections = np.inner(points.reshape(points.size / 3, 3) -
    #                        self.position, self.orientation)

    projections = np.inner(points - self.position, self.orientation)

    # Rescale to screen distance:
    projections *= np.abs(self.distance /
                          projections[:, :, np.newaxis, 1])

    # Change origin to upper-left corner of screen:
    projections += np.array([self.screen.width * 0.5 - self.screen.u, 0.0,
                             -self.screen.height * 0.5 - self.screen.w])

    # Convert to left-handed pixel space and return:
    return np.round(projections[:, :, (self.U, self.W)] * self._norms *
                    np.array([1, -1])
                    ).astype(int), projections[:, :, self.V]

    return np.round(np.array(
        [ projections[:, :, self.U] * self._norms[self.X],
         -projections[:, :, self.W] * self._norms[self.Y]]).T
        ).astype(int), projections[:, :, self.V]

</t>
<t tx="karstenw.20230817121914.43">def look_at_point(self, point):
    roll = self.get_roll()

    delta = point - self.position
    v = delta / np.linalg.norm(delta)
    u = np.cross(v, np.array([0.0, 0.0, 1.0]))
    u /= np.linalg.norm(u)
    w = np.cross(u, v)

    # This is clumsy:
    self.orientation = np.c_[u, v, w].T

    # This is not implemented:
    self.set_roll(roll)

</t>
<t tx="karstenw.20230817121914.44">def get_azimuth(self):
    return np.arctan2(self.v[self.Y], self.v[self.X])

</t>
<t tx="karstenw.20230817121914.45">def get_elevation(self):
    return np.arcsin(self.v[self.W])

</t>
<t tx="karstenw.20230817121914.46">def get_roll(self):
    u = np.cross(self.v, np.array([0.0, 0.0, 1.0]))

    return np.arctan2(np.dot(self.v, np.cross(u, self.u)),
                      np.dot(u, self.u))

</t>
<t tx="karstenw.20230817121914.47">def set_roll(self, roll):
    # print "Sorry! set_roll() is not yet implemented.!"
    pass
</t>
<t tx="karstenw.20230817121914.5">@position.setter
def position(self, val):
    self._position = val

</t>
<t tx="karstenw.20230817121914.6">@property
def extent(self):
    return self._extent

</t>
<t tx="karstenw.20230817121914.7">@extent.setter
def extent(self, val):
    self._extent = val

</t>
<t tx="karstenw.20230817121914.8">@property
def resolution(self):
    return self._resolution

</t>
<t tx="karstenw.20230817121914.9">@resolution.setter
def resolution(self, val):
    self._resolution = val

</t>
<t tx="karstenw.20230817121932.1">import numpy as np


</t>
<t tx="karstenw.20230817121932.10">def map_positions_slice(self, position, view):
    """
    Returns a slice of the map positions centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    the_slice = self._positions[X, Y, :]

    # Fix periodicity:
    the_slice = self.fix_view(position, view, the_slice)

    return the_slice

</t>
<t tx="karstenw.20230817121932.11">def patch_positions_slice(self, position, view):
    """
    Returns a slice of the patch positions centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    the_slice = self._positions[X, Y, :]

    # Fix periodicity:
    the_slice = self.fix_view(position, view, the_slice)

    return the_slice

</t>
<t tx="karstenw.20230817121932.12">def normals_slice(self, position, view):
    """
    Returns a slice of the map normals centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._normals[X, Y, :]

</t>
<t tx="karstenw.20230817121932.13">def colours_slice(self, position, view):
    """
    Returns a slice of the map colours centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._colours[X, Y, :]

</t>
<t tx="karstenw.20230817121932.14">def patches_list(self, position, view):
    """
    Returns patches as a list for use in Camera etc.
    """

    the_slice = self.patches_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 4, 3))

</t>
<t tx="karstenw.20230817121932.15">def map_positions_list(self, position, view):
    """
    Returns positions as a list for use in Camera etc.
    """

    the_slice = self.map_positions_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 3))

</t>
<t tx="karstenw.20230817121932.16">def patch_positions_list(self, position, view):
    """
    Returns positions as a list for use in Camera etc.
    """

    the_slice = self.patch_positions_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 3))

</t>
<t tx="karstenw.20230817121932.17">def normals_list(self, position, view):
    """
    Returns normals as a list for use in Camera etc.
    """
    the_slice = self.normals_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 3))

</t>
<t tx="karstenw.20230817121932.18">def colours_list(self, position, view):
    """
    Returns colours as a list for use in Camera etc.
    """
    the_slice = self.colours_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 4))

</t>
<t tx="karstenw.20230817121932.19">@property
def patches(self):
    """
    Returns patches in native shape.
    """

    return self._patches

</t>
<t tx="karstenw.20230817121932.2">class Map(object):
    """
    The Map class contains data for displaying/rendering a map of an area.

    The data is:
    * patches:
        - semi-rectangular patches that are the units of the map

    * positions:
        - positions of the patches, calculated as the man of the patches'
          corner positions.

    * normals:
        - an approximation of the normal to the patches, useful for shading.

    * sealevel:
        - a minimum level, under witch patches will not extend.

    * colours:
        - per-patch colour triplet, randomly assigned based on distance to
          sealevel and such.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121932.20">@property
def map_positions(self):
    """
    Returns positions in native shape.
    """

    return self._positions

</t>
<t tx="karstenw.20230817121932.21">@property
def patch_positions(self):
    """
    Returns positions in native shape.
    """

    return self._positions

</t>
<t tx="karstenw.20230817121932.22">@property
def normals(self):
    """
    Returns normals in native shape.
    """
    return self._normals

</t>
<t tx="karstenw.20230817121932.23">@property
def colours(self):
    """
    Returns colours in native shape.
    """
    return self._colours

</t>
<t tx="karstenw.20230817121932.24">def fix_view(self, position, view, positions):
    xmin = position[self.X] - view[self.X] * 0.5
    xmax = position[self.X] + view[self.X] * 0.5
    ymin = position[self.Y] - view[self.Y] * 0.5
    ymax = position[self.Y] + view[self.Y] * 0.5

    # Fix periodicity:
    if xmin &lt;= 0.0:

        positions[..., self.X] = ((positions[..., self.X] +
                                   view[self.X] * 0.5 + 0.5) %
                                  self.shape[self.X] -
                                  view[self.X] * 0.5 - 0.5)

    elif xmax &gt;= self.shape[self.X] - 1.0:

        positions[..., self.X] = ((positions[..., self.X] -
                                   view[self.X] * 0.5 - 1.0) %
                                  self.shape[self.X] +
                                  view[self.X] * 0.5 + 1.0)

    if ymin &lt;= 0.0:

        positions[..., self.Y] = ((positions[..., self.Y] +
                                   view[self.Y] * 0.5 + 0.5) %
                                  self.shape[self.Y] -
                                  view[self.Y] * 0.5 - 0.5)

    elif ymax &gt;= self.shape[self.Y] - 1.0:

        positions[..., self.Y] = ((positions[..., self.Y] -
                                   view[self.Y] * 0.5 - 1.0) %
                                  self.shape[self.Y] +
                                  view[self.Y] * 0.5 + 1.0)
    return positions

</t>
<t tx="karstenw.20230817121932.25">def positions_in_view(self, position, view, positions):
    xmin = position[self.X] - view[self.X] * 0.5
    xmax = position[self.X] + view[self.X] * 0.5
    ymin = position[self.Y] - view[self.Y] * 0.5
    ymax = position[self.Y] + view[self.Y] * 0.5

    return np.where((positions[:, self.X] &gt;= xmin) *
                    (positions[:, self.X] &lt;= xmax) *
                    (positions[:, self.Y] &gt;= ymin) *
                    (positions[:, self.Y] &lt;= ymax))[0]

</t>
<t tx="karstenw.20230817121932.26">def _make_patches(self):
    """
    Create patches made up of four points (corners of squares in the
    xy-plane).
    """

    # Ininitalise patches:
    xsize, ysize = self.shape
    patches = np.zeros((xsize, ysize, 4, 3))

    # Fill patches:
    # These for-loops could be removed:
    for x in range(xsize):
        for y in range(ysize):
            xinds = np.array([x, x + 1, x + 1, x])
            yinds = np.array([y, y, y + 1, y + 1])
            patches[x, y, :, 0] = xinds - 0.5
            patches[x, y, :, 1] = yinds - 0.5
            patches[x, y, :, 2] = self.raw_map[yinds, xsize - xinds]

    self._patches = patches

</t>
<t tx="karstenw.20230817121932.27">def _colourise(self):
    """
    Not yet fully implemented, but should assign colours (with some sort of
    noise) to patches.

    Currently debug wit just green and blue.
    """
    colours = np.zeros([self._patches.shape[0], self._patches.shape[1], 4],
                       dtype=int)

    max_height = self._positions[:, :, self.Z].max()
    for x in range(colours.shape[self.X]):
        for y in range(colours.shape[self.Y]):
            height = self._positions[x, y, self.Z]
            if height &gt; self.sealevel + 0.14:
                colours[x, y] = np.array([51, 102, 26, 255]) + np.array(
                    [np.random.random() * height / max_height,
                     np.random.random() * (1 - height / max_height),
                     0, 0]) * 153
            elif height &lt; self.sealevel - 0.28:
                colours[x, y] = np.array([1, 1, 77, 255])
            else:
                colours[x, y] = np.array([204, 153, 51, 255]) + np.array(
                    [np.random.random() * height / max_height,
                     np.random.random() * height / max_height,
                     0, 0]) * 153

    self._colours = colours

</t>
<t tx="karstenw.20230817121932.28">def _calc_positions(self):
    """
    Useful for sorting and the like.
    """

    self._positions = self._patches.mean(2)

</t>
<t tx="karstenw.20230817121932.29">def _calc_normals(self):
    """
    This is a little bit arbitrary since the normal is not well defined
    for patches, but it is arbitrary in a very systematic way and therefore
    gives a nice noise effect (hopefully).
    """

    normals = np.zeros([self._patches.shape[0], self._patches.shape[1], 3])

    v0s = self._patches[:, :, 1] - self._patches[:, :, 0]
    v1s = self._patches[:, :, 2] - self._patches[:, :, 1]
    v2s = self._patches[:, :, 3] - self._patches[:, :, 2]
    v3s = self._patches[:, :, 0] - self._patches[:, :, 3]

    normals = np.cross(v0s, v1s + v3s) + np.cross(v2s, v3s - v1s)
    normals /= np.sqrt((normals ** 2).sum(-1))[:, :, np.newaxis]

    self._normals = normals

</t>
<t tx="karstenw.20230817121932.3">def __init__(self, filename='demodata.npy', sealevel=0, flat_sea=True):
    if filename is None:
        self._raw_map = np.zeros([10, 13])
    else:
        self._raw_map = np.load(filename)

    self._sealevel = sealevel

    self._flat_sea = flat_sea

    self._make_patches()

    self._size = self._patches.size / 12

    self._calc_positions()

    if self._flat_sea:
        self._flood()

    self._calc_normals()

    self._colourise()

    if not self._flat_sea:
        self._flood()

</t>
<t tx="karstenw.20230817121932.30">def _flood(self):
    """
    Raises patch-points that are under the sealevel to the sealevel to
    ensure a flat sea.

    If run after calc_normals(), this should give an interesting shading
    effect.

    If run after calc_positions() it opens for the opportunity of going
    under water some time in the future, and gives "breaking waves"
    on shores.
    """

    self._patches[:, :, :, 2] = np.where(
        self._patches[:, :, :, 2] &lt; self.sealevel, self.sealevel,
        self._patches[:, :, :, 2])

</t>
<t tx="karstenw.20230817121932.31">def reflood(self, sealevel, flat_sea=False):
    self._sealevel = sealevel

    self._flat_sea = flat_sea

    self._make_patches()

    self._calc_positions()

    if self.flat_sea:
        self._flood()

    self._calc_normals()

    self._colourise()

    if not self.flat_sea:
        self._flood()


</t>
<t tx="karstenw.20230817121932.32">class TriMap(object):
    """
    NOT UP TO DATE!
    The Map class contains data for displaying/rendering a map of an area.

    The data is:
    * patches:
        - sets of four triangular patches that are the units of the map

    * positions:
        - positions of the patches, calculated as the man of the patches'
          corner positions.

    * normals:
        - an approximation of the normal to the patches, useful for shading.

    * sealevel:
        - a minimum level, under witch patches will not extend.

    * colours:
        - per-patch colour triplet, randomly assigned based on distance to
          sealevel and such.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121932.33">def __init__(self, filename='demodata.npy', sealevel=0, flat_sea=True):
    if filename is None:
        self._raw_map = np.zeros([10, 13])
    else:
        self._raw_map = np.load(filename)

    self._sealevel = sealevel

    self._flat_sea = flat_sea

    self._make_patches()

    self._size = self._patches.size / 12

    self._calc_positions()

    if self._flat_sea:
        self._flood()

    self._calc_normals()

    self._colourise()

    if not self._flat_sea:
        self._flood()

</t>
<t tx="karstenw.20230817121932.34">@property
def sealevel(self):
    return self._sealevel

</t>
<t tx="karstenw.20230817121932.35">@property
def shape(self):
    return (self._raw_map.shape[1] - 1, self._raw_map.shape[0] - 1)

</t>
<t tx="karstenw.20230817121932.36">@property
def flat_sea(self):
    return self._flat_sea

</t>
<t tx="karstenw.20230817121932.37">@property
def raw_map(self):
    return self._raw_map

</t>
<t tx="karstenw.20230817121932.38">def slice(self, position, view):
    the_position = np.round(position).astype(int)

    Y, X = np.mgrid[the_position[self.Y] - view[self.Y] / 2 - 1:
                    the_position[self.Y] + view[self.Y] / 2 + 1,
                    the_position[self.X] - view[self.X] / 2 - 1:
                    the_position[self.X] + view[self.X] / 2 + 1]

    X %= self.shape[self.X]
    Y %= self.shape[self.Y]

    return X, Y

</t>
<t tx="karstenw.20230817121932.39">def patches_slice(self, position, view):
    """
    Returns a slice of the map patches centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._patches[X, Y, :]

</t>
<t tx="karstenw.20230817121932.4">@property
def sealevel(self):
    return self._sealevel

</t>
<t tx="karstenw.20230817121932.40">def patch_positions_slice(self, position, view):
    """
    Returns a slice of the patch positions centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._patch_positions[X, Y, :]

</t>
<t tx="karstenw.20230817121932.41">def map_positions_slice(self, position, view):
    """
    Returns a slice of the map positions centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._map_positions[X, Y, :]

</t>
<t tx="karstenw.20230817121932.42">def normals_slice(self, position, view):
    """
    Returns a slice of the map normals centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._normals[X, Y, :]

</t>
<t tx="karstenw.20230817121932.43">def colours_slice(self, position, view):
    """
    Returns a slice of the map colours centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    return self._colours[X, Y, :]

</t>
<t tx="karstenw.20230817121932.44">def patches_list(self, position, view):
    """
    Returns patches as a list for use in Camera etc.
    """

    the_slice = self.patches_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size * 4, 3, 3))

</t>
<t tx="karstenw.20230817121932.45">def map_positions_list(self, position, view):
    """
    Returns map positions as a list for use in Camera etc.
    """

    the_slice = self.map_positions_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size, 3))

</t>
<t tx="karstenw.20230817121932.46">def patch_positions_list(self, position, view):
    """
    Returns patch positions as a list for use in Camera etc.
    """

    the_slice = self.patch_positions_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size * 4, 3))

</t>
<t tx="karstenw.20230817121932.47">def normals_list(self, position, view):
    """
    Returns normals as a list for use in Camera etc.
    """
    the_slice = self.normals_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size * 4, 3))

</t>
<t tx="karstenw.20230817121932.48">def colours_list(self, position, view):
    """
    Returns colours as a list for use in Camera etc.
    """
    the_slice = self.colours_slice(position, view)
    size = the_slice.shape[0] * the_slice.shape[1]

    return the_slice.reshape((size * 4, 4))

</t>
<t tx="karstenw.20230817121932.49">@property
def patches(self):
    """
    Returns patches in native shape.
    """

    return self._patches

</t>
<t tx="karstenw.20230817121932.5">@property
def shape(self):
    return (self._raw_map.shape[1] - 1, self._raw_map.shape[0] - 1)

</t>
<t tx="karstenw.20230817121932.50">@property
def map_positions(self):
    """
    Returns positions in native shape.
    """

    return self._map_positions

</t>
<t tx="karstenw.20230817121932.51">@property
def patch_positions(self):
    """
    Returns positions in native shape.
    """

    return self._patch_positions

</t>
<t tx="karstenw.20230817121932.52">@property
def normals(self):
    """
    Returns normals in native shape.
    """
    return self._normals

</t>
<t tx="karstenw.20230817121932.53">@property
def colours(self):
    """
    Returns colours in native shape.
    """
    return self._colours

</t>
<t tx="karstenw.20230817121932.54">def _make_patches(self):
    """
    Create patches made up of three points, dividing the squares into four
    triangles.
    """

    # Ininitalise patches:
    xsize, ysize = self.shape
    patches = np.zeros((xsize, ysize, 4, 3, 3))

    # Fill patches:
    # This for-looops could and should be removed:
    for x in range(xsize):
        for y in range(ysize):
            xinds = np.array([x, x + 1, x + 1, x, x])
            yinds = np.array([y, y, y + 1, y + 1, y])
            xcentre = xinds[: 4].mean() - 0.5
            ycentre = yinds[: 4].mean() - 0.5
            zcentre = self.raw_map[yinds, xsize - xinds].mean()
            for n in range(4):
                patches[x, y, n, :, 0] = np.r_[xinds[n: n + 2] - 0.5,
                                               xcentre]
                patches[x, y, n, :, 1] = np.r_[yinds[n: n + 2] - 0.5,
                                               ycentre]
                patches[x, y, n, :, 2] = np.r_[self.raw_map[
                    yinds[n: n + 2], xsize - xinds[n: n + 2]], zcentre]

    self._patches = patches

</t>
<t tx="karstenw.20230817121932.55">def _colourise(self):
    """
    Not yet fully implemented, but should assign colours (with some sort of
    noise) to patches.

    Currently debug wit just green and blue.
    """
    colours = np.zeros([self._patches.shape[0], self._patches.shape[1], 4,
                        4], dtype=int)

    for x in range(colours.shape[0]):
        for y in range(colours.shape[1]):
            if self._map_positions[x, y, 2] &gt; self.sealevel:
                colours[x, y, :] = np.array([102, 153, 0, 255])
            else:
                colours[x, y, :] = np.array([0, 0, 77, 255])

    self._colours = colours

</t>
<t tx="karstenw.20230817121932.56">def _calc_positions(self):
    """
    Useful for sorting and the like.
    """

    self._patch_positions = self._patches.mean(3)
    self._map_positions = self._patch_positions.mean(2)

</t>
<t tx="karstenw.20230817121932.57">def _calc_normals(self):
    """
    This is a little bit arbitrary since the normal is not well defined
    for patches, but it is arbitrary in a very systematic way and therefore
    gives a nice noise effect (hopefully).
    """

    normals = np.zeros([self._patches.shape[0], self._patches.shape[1], 4,
                        3])

    v0s = self._patches[:, :, :, 1] - self._patches[:, :, :, 0]
    v1s = self._patches[:, :, :, 2] - self._patches[:, :, :, 1]

    normals = np.cross(v0s, v1s)
    normals /= np.sqrt((normals ** 2).sum(-1))[:, :, :, np.newaxis]

    self._normals = normals

</t>
<t tx="karstenw.20230817121932.58">def _flood(self):
    """
    Raises patch-points that are under the sealevel to the sealevel to
    ensure a flat sea.

    If run after calc_normals(), this should give an interesting shading
    effect.

    If run after calc_positions() it opens for the opportunity of going
    under water some time in the future, and gives "breaking waves"
    on shores.
    """

    self._patches[:, :, :, :, 2] = np.where(
        self._patches[:, :, :, :, 2] &lt; self.sealevel, self.sealevel,
        self._patches[:, :, :, :, 2])

</t>
<t tx="karstenw.20230817121932.59">def reflood(self, sealevel, flat_sea=False):
    self._sealevel = sealevel

    self._flat_sea = flat_sea

    self._make_patches()

    self._calc_positions()

    if self.flat_sea:
        self._flood()

    self._calc_normals()

    self._colourise()

    if not self.flat_sea:
        self._flood()
</t>
<t tx="karstenw.20230817121932.6">@property
def flat_sea(self):
    return self._flat_sea

</t>
<t tx="karstenw.20230817121932.7">@property
def raw_map(self):
    return self._raw_map

</t>
<t tx="karstenw.20230817121932.8">def slice(self, position, view):
    xmin = np.round(position[self.X] - view[self.X] * 0.5).astype(int)
    xmax = np.round(position[self.X] + view[self.X] * 0.5).astype(int)
    ymin = np.round(position[self.Y] - view[self.Y] * 0.5).astype(int)
    ymax = np.round(position[self.Y] + view[self.Y] * 0.5).astype(int)

    Y, X = np.mgrid[ymin: ymax + 1, xmin: xmax + 1]

    X %= self.shape[self.X]
    Y %= self.shape[self.Y]

    return X, Y

</t>
<t tx="karstenw.20230817121932.9">def patches_slice(self, position, view):
    """
    Returns a slice of the map patches centered on position, with
    dimensions decided by view.
    """

    X, Y = self.slice(position, view)

    xmin = position[self.X] - view[self.X] * 0.5
    xmax = position[self.X] + view[self.X] * 0.5
    ymin = position[self.Y] - view[self.Y] * 0.5
    ymax = position[self.Y] + view[self.Y] * 0.5

    the_slice = self._patches[X, Y, :]

    # Fix periodicity:
    the_slice = self.fix_view(position, view, the_slice)

    # Impose view limits:
    the_slice[:, 0, (3, 0), self.Z] += ((the_slice[:, 0, (2, 1), self.Z] -
                                         the_slice[:, 0, (3, 0), self.Z])
                                        * (xmin - the_slice[:, 0, (3, 0),
                                                            self.X]))

    the_slice[:, -1, (2, 1), self.Z] += ((the_slice[:, -1, (2, 1), self.Z]
                                          - the_slice[:, -1, (3, 0),
                                                      self.Z]) *
                                         (xmax - the_slice[:, -1, (2, 1),
                                                           self.X]))

    the_slice[0, :, (0, 1), self.Z] += ((the_slice[0, :, (3, 2), self.Z] -
                                         the_slice[0, :, (0, 1), self.Z])
                                        * (ymin - the_slice[0, :, (0, 1),
                                                            self.Y]))

    the_slice[-1, :, (3, 2), self.Z] += ((the_slice[-1, :, (3, 2), self.Z]
                                          - the_slice[-1, :, (0, 1),
                                                      self.Z]) *
                                         (ymax - the_slice[-1, :, (3, 2),
                                                           self.Y]))

    the_slice[:, 0, (3, 0), self.X] = xmin
    the_slice[:, -1, (1, 2), self.X] = xmax
    the_slice[0, :, (0, 1), self.Y] = ymin
    the_slice[-1, :, (2, 3), self.Y] = ymax

    return the_slice

</t>
<t tx="karstenw.20230817121937.1">import numpy as np


</t>
<t tx="karstenw.20230817121937.10">@property
def pitch(self):
    return self._model.pitch

@pitch.setter
def pitch(self, val):
    self._model.pitch = val

</t>
<t tx="karstenw.20230817121937.12">@property
def roll(self):
    return self._model.roll

@roll.setter
def roll(self, val):
    self._model.roll = val

</t>
<t tx="karstenw.20230817121937.13">@property
def bounding_box(self):
    return self._model.bounding_box

</t>
<t tx="karstenw.20230817121937.15">@property
def velocity(self):
    return self._velocity

@velocity.setter
def velocity(self, val):
    self._velocity = val

</t>
<t tx="karstenw.20230817121937.17">@property
def acceleration(self):
    return self._acceleration

@acceleration.setter
def acceleration(self, val):
    self._acceleration = val

</t>
<t tx="karstenw.20230817121937.19">@property
def inertia(self):
    return self._inertia

@inertia.setter
def inertia(self, val):
    self._inertia = val

</t>
<t tx="karstenw.20230817121937.2">class Movable(object):
    """
    Parent class for movable objects.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121937.20">@property
def gravity(self):
    return self._gravity * np.array([0, 0, -1])

@gravity.setter
def gravity(self, val):
    self._gravity = val

</t>
<t tx="karstenw.20230817121937.23">@property
def friction(self):
    return -self._friction * self._velocity

@friction.setter
def friction(self, val):
    self._friction = val

</t>
<t tx="karstenw.20230817121937.24">def move(self, dt=0.03125):
    self.apply_forces()
    self.velocity += self.acceleration * dt
    self.position += self.velocity * dt

</t>
<t tx="karstenw.20230817121937.25">def apply_forces(self):
    force = self.friction + self.gravity * self.inertia
    self.acceleration = force / self.inertia

</t>
<t tx="karstenw.20230817121937.26">def bounce(self, world):
    normal = world.normals[int(self.position[self.X]),
                           int(self.position[self.Y])]
    self._velocity -= 2.0 * np.dot(self._velocity, normal) * normal

</t>
<t tx="karstenw.20230817121937.27">def impose_boundary_conditions(self, world):
    self.position[self.X] %= world.shape[self.X]
    self.position[self.Y] %= world.shape[self.Y]

    height = max(0, world.patches[int(self.position[self.X]),
                                  int(self.position[self.Y]),
                                  :, self.Z].max())

    if self.model.bounding_box[0, self.Z] &lt; height:
        self.position[self.Z] += (height -
                                  self.model.bounding_box[0, self.Z])
        self.bounce(world)
        if abs(self.velocity[self.Z]) &gt; 2.5:
            self.model.exploding = True
    elif self.position[self.Z] &gt; 36.0 and self.velocity[self.Z] &gt; 0:
        self.velocity[self.Z] *= 0.9
        if self.acceleration[self.Z] &gt; 0:
            self.acceleration[self.Z] = 0.0


</t>
<t tx="karstenw.20230817121937.28">class Player(Movable):
    """
    Player object has health, fuel etc.
    """

    @others
</t>
<t tx="karstenw.20230817121937.29">def __init__(self, model, inertia=1.0, gravity=5.0, friction=0.5,
             position=np.array([0.0, 0.0, 0.0]),
             velocity=np.array([0.0, 0.0, 0.0]),
             acceleration=np.array([0.0, 0.0, 0.0]),
             yaw=0.0, pitch=0.0, roll=0.0,
             fuel=255, rockets=3, health=255, bombs=3, cool_down=0.0625):

    self._model = model
    self._inertia = inertia
    self._gravity = gravity
    self._friction = friction
    self._position = position
    self._velocity = velocity
    self._acceleration = acceleration

    self._model.position = position
    self._model.yaw = yaw
    self._model.pitch = pitch
    self._model.roll = roll

    self._fuel = fuel
    self._rockets = rockets
    self._health = health
    self._bombs = bombs
    self._cool_down = cool_down

    self._thrust = False
    self._fire = False
    self._rocket = False
    self._bomb = False

</t>
<t tx="karstenw.20230817121937.3">def __init__(self, model, inertia=1.0, gravity=1.0, friction=1.0,
             position=np.array([0.0, 0.0, 0.0]),
             velocity=np.array([0.0, 0.0, 0.0]),
             acceleration=np.array([0.0, 0.0, 0.0]),
             yaw=0.0, pitch=0.0, roll=0.0):

    self._model = model
    self._inertia = inertia
    self._gravity = gravity
    self._friction = friction
    self._position = position
    self._velocity = velocity
    self._acceleration = acceleration

    self._model.position = position
    self._model.yaw = yaw
    self._model.pitch = pitch
    self._model.roll = roll

</t>
<t tx="karstenw.20230817121937.30">@property
def fuel(self):
    return self._fuel

@fuel.setter
def fuel(self, val):

    if val &gt; 255:

        val = 255

    elif val &lt; 0:

        val = 0

    self._fuel = val

</t>
<t tx="karstenw.20230817121937.33">@property
def health(self):
    return self._health

@health.setter
def health(self, val):

    if val &gt; 255:

        val = 255

    elif val &lt; 0:

        val = 0

    self._health = val

</t>
<t tx="karstenw.20230817121937.35">@property
def rockets(self):
    return self._rockets

@rockets.setter
def rockets(self, val):

    if val &gt; 3:

        val = 3

    elif val &lt; 0:

        val = 0

    self._rockets = val

</t>
<t tx="karstenw.20230817121937.37">@property
def bombs(self):
    return self._bombs

@bombs.setter
def bombs(self, val):

    if val &gt; 3:

        val = 3

    elif val &lt; 0:

        val = 0

    self._bombs = val

</t>
<t tx="karstenw.20230817121937.39">@property
def thrust(self):
    return self._thrust

@thrust.setter
def thrust(self, val):
    self._thrust = val and True

</t>
<t tx="karstenw.20230817121937.4">@property
def model(self):
    return self._model

</t>
<t tx="karstenw.20230817121937.41">@property
def rocket(self):
    return self._rocket

@rocket.setter
def rocket(self, val):
    self._rocket = val and True

</t>
<t tx="karstenw.20230817121937.43">@property
def fire(self):
    return self._fire

@fire.setter
def fire(self, val):
    self._fire = val and True

</t>
<t tx="karstenw.20230817121937.44">@property
def bomb(self):
    return self._bomb

@bomb.setter
def bomb(self, val):
    self._bomb = val and True

</t>
<t tx="karstenw.20230817121937.46"># UNUSED
@property
def cool_down(self):
    return self._cool_down

@cool_down.setter
def cool_down(self, val):
    self._cool_down = val

</t>
<t tx="karstenw.20230817121937.48">def apply_forces(self):
    force = (   self.friction
              + self.gravity * self.inertia
              + 20 * (
                 self.thrust
                 and self.position[self.Z] &lt; 36.0
                 and not self.model.exploding )
              * self.model.orientation[self.W])

    self.acceleration = force / self.inertia

    if self.model.exploding:
        self.model.explode()
</t>
<t tx="karstenw.20230817121937.6">@property
def position(self):
    return self._position

@position.setter
def position(self, val):
    self._position = val
    self._model.position = val

</t>
<t tx="karstenw.20230817121937.8">@property
def yaw(self):
    return self._model.yaw

@yaw.setter
def yaw(self, val):
    self._model.yaw = val

</t>
<t tx="karstenw.20230817121939.1">import numpy as np
from . import triDobjects as tD


</t>
<t tx="karstenw.20230817121939.10">@property
def patches(self):
    self._model.yaw = np.random.random() * 2 * np.pi
    self._model.pitch = np.random.random() * 2 * np.pi
    self._model.roll = np.random.random() * 2 * np.pi
    return self._model.patches

</t>
<t tx="karstenw.20230817121939.12">@property
def colour(self):
    return self._colour

@colour.setter
def colour(self, val):
    self._colour = val

</t>
<t tx="karstenw.20230817121939.14">@property
def lifetime(self):
    return self._lifetime

@lifetime.setter
def lifetime(self, val):
    self._lifetime = val

</t>
<t tx="karstenw.20230817121939.16">@property
def elasticity(self):
    return self._elasticity

@elasticity.setter
def elasticity(self, val):
    self._elasticity = val


</t>
<t tx="karstenw.20230817121939.17">class Particles(object):

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121939.18">def __init__(self, particle=Particle()):
    self._particle = particle
    self._positions = np.empty((0, 3))
    self._velocities = np.empty((0, 3))
    self._accelerations = np.empty((0, 3))
    self._ages = np.empty((0))
    self._colours = np.empty((0, 4))
    self._visible = True

</t>
<t tx="karstenw.20230817121939.19">@property
def particle(self):
    return self._particle

</t>
<t tx="karstenw.20230817121939.2">class Particle(object):
    """
    Parent class for particles.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121939.20">@particle.setter
def particle(self, val):
    self._particle = val

</t>
<t tx="karstenw.20230817121939.21">@property
def number(self):
    return self.positions.shape[0]

</t>
<t tx="karstenw.20230817121939.22">@property
def visible(self):
    return self._visible

</t>
<t tx="karstenw.20230817121939.23">@visible.setter
def visible(self, val):
    self._visible = val

</t>
<t tx="karstenw.20230817121939.24">@property
def positions(self):
    return self._positions

</t>
<t tx="karstenw.20230817121939.25">@positions.setter
def positions(self, val):
    self._positions = val

</t>
<t tx="karstenw.20230817121939.26">@property
def patch_positions(self):
    return (self.positions[:, np.newaxis, np.newaxis, :] +
            self.particle.patches[np.newaxis, :, :, :]).mean(-2).reshape(
                self.number * 4, 3)

</t>
<t tx="karstenw.20230817121939.27">@property
def patches(self):
    return (self.positions[:, np.newaxis, np.newaxis, :] +
            self.particle.patches[np.newaxis, :, :, :]).reshape(
                self.number * 4, 3, 3)

</t>
<t tx="karstenw.20230817121939.28">@property
def velocities(self):
    return self._velocities

</t>
<t tx="karstenw.20230817121939.29">@velocities.setter
def velocities(self, val):
    self._velocities = val

</t>
<t tx="karstenw.20230817121939.3">def __init__(self, inertia=1.0, gravity=1.0, friction=0.05, size=0.03,
             colour=np.array([255, 255, 153, 255]), lifetime=2.0,
             elasticity=1.0):

    self._inertia = inertia
    self._gravity = gravity
    self._friction = friction
    self._size = size
    self._colour = colour
    self._lifetime = lifetime
    self._elasticity = elasticity
    self._model = tD.TriD(scale=size)

</t>
<t tx="karstenw.20230817121939.31">@property
def accelerations(self):
    return self._accelerations

@accelerations.setter
def accelerations(self, val):
    self._accelerations = val

</t>
<t tx="karstenw.20230817121939.33">@property
def ages(self):
    return self._ages

@ages.setter
def ages(self, val):
    self._ages = val

</t>
<t tx="karstenw.20230817121939.35">@property
def colours(self):
    return self._colours

@colours.setter
def colours(self, val):
    self._colours = val

</t>
<t tx="karstenw.20230817121939.36">@property
def patch_colours(self):
    return (self._colours * np.ones((4, 1, 1))).reshape(self.number * 4, 4)

</t>
<t tx="karstenw.20230817121939.37">def move(self, dt=0.03125):
    self.apply_forces()
    self.velocities += self.accelerations * dt
    self.positions += self.velocities * dt
    self.ages += dt

</t>
<t tx="karstenw.20230817121939.38">def apply_forces(self):
    forces = (-self.particle.friction * self.velocities +
              self.particle.gravity * self.particle.inertia)
    self.accelerations = forces / self.particle.inertia

</t>
<t tx="karstenw.20230817121939.39">def bounce(self, world, n):
    normals = world.normals[int(self.positions[n, self.X]),
                            int(self.positions[n, self.Y])]
    self.velocities[n] -= ((1 + self.particle.elasticity) * normals *
                           (self.velocities[n] *
                            normals).sum(-1)[..., np.newaxis])

</t>
<t tx="karstenw.20230817121939.40">def impose_boundary_conditions(self, world):
    self.cull_aged()

    self.positions[:, self.X] %= world.shape[self.X]
    self.positions[:, self.Y] %= world.shape[self.Y]

    heights = world.map_positions[
        self.positions[:, self.X].astype(int),
        self.positions[:, self.Y].astype(int), self.Z]

    heights = np.where(heights &lt; 0, 0, heights)

    bouncers = np.where(self.positions[:, self.Z] &lt; heights)[0]
    for n in bouncers:
        self.positions[n, self.Z] = heights[n]
        self.bounce(world, n)

</t>
<t tx="karstenw.20230817121939.41">def add_particle(self, position, velocity, acceleration, age=0.0,
                 colour=None):
    self.positions = np.r_[self.positions, position[np.newaxis]]
    self.velocities = np.r_[self.velocities, velocity[np.newaxis]]
    self.accelerations = np.r_[self.accelerations,
                               acceleration[np.newaxis]]
    self.ages = np.r_[self.ages, age]
    if colour is None:
        self.colours = np.r_[self.colours,
                             self.particle.colour[np.newaxis]]
    else:
        self.colours = np.r_[self.colours, colour[np.newaxis]]

</t>
<t tx="karstenw.20230817121939.42">def delete_particle(self, n):
    indices = np.r_[np.arange(n), np.arange(self.positions.shape[0])]
    self.positions = self.positions[indices]
    self.velocities = self.velocities[indices]
    self.accelerations = self.accelerations[indices]
    self.ages = self.ages[indices]
    self.colours = self.colours[indices]

</t>
<t tx="karstenw.20230817121939.43">def delete_particles(self, to_delete):
    indices = np.setdiff1d(np.arange(self.number), to_delete)
    self.positions = self.positions[indices]
    self.velocities = self.velocities[indices]
    self.accelerations = self.accelerations[indices]
    self.ages = self.ages[indices]
    self.colours = self.colours[indices]

</t>
<t tx="karstenw.20230817121939.44">def cull_aged(self):
    if (self.ages &gt; self.particle.lifetime).any():
        indices = np.where(self.ages &gt; self.particle.lifetime)[0]
        self.delete_particles(indices)


</t>
<t tx="karstenw.20230817121939.45">class Shots(Particles):
    @others
</t>
<t tx="karstenw.20230817121939.46">def __init__(self, particle=Particle()):
    self._particle = particle
    self._positions = np.empty((0, 3))
    self._velocities = np.empty((0, 3))
    self._accelerations = np.empty((0, 3))
    self._ages = np.empty((0))
    self._colours = np.empty((0, 4))
    self._visible = True

</t>
<t tx="karstenw.20230817121939.47">def impose_boundary_conditions(self, world):
    self.cull_aged()

    if self.number:
        self.positions[:, self.X] %= world.shape[self.X]
        self.positions[:, self.Y] %= world.shape[self.Y]

        heights = world.map_positions[
            self.positions[:, self.X].astype(int),
            self.positions[:, self.Y].astype(int), self.Z]

        heights = np.where(heights &lt; 0, 0, heights)

        bouncers = np.where(self.positions[:, self.Z] &lt; heights)[0]
        if bouncers.size:
            positions = self.positions[bouncers]

            velocities = self.velocities[bouncers]

            mixing = (
                np.random.random(bouncers.shape)
                * (positions[:, self.Z] &lt;= 0)
            )
            colours = np.clip(world.colours[
                self.positions[bouncers, self.X].astype(int),
                self.positions[bouncers, self.Y].astype(int),
            ] + 64 * mixing[:, np.newaxis], 0, 255)

            self.delete_particles(bouncers)

            return positions, velocities, colours

</t>
<t tx="karstenw.20230817121939.48">def cull_aged(self):
    if self.ages[0] &gt; self.particle.lifetime:
        self.positions = self.positions[1:]
        self.velocities = self.velocities[1:]
        self.accelerations = self.accelerations[1:]
        self.ages = self.ages[1:]
        self.colours = self.colours[1:]


</t>
<t tx="karstenw.20230817121939.49">class Shrapnel(Particles):
    @others
</t>
<t tx="karstenw.20230817121939.5">@property
def inertia(self):
    return self._inertia

@inertia.setter
def inertia(self, val):
    self._inertia = val

</t>
<t tx="karstenw.20230817121939.50">def __init__(self, particle=Particle(friction=0.5, lifetime=0.5,
                                     elasticity=np.sqrt(3) * 0.5)):
    self._particle = particle
    self._positions = np.empty((0, 3))
    self._velocities = np.empty((0, 3))
    self._accelerations = np.empty((0, 3))
    self._ages = np.empty((0))
    self._colours = np.empty((0, 4))
    self._visible = True

</t>
<t tx="karstenw.20230817121939.51">def add_particles(self, positions, velocities, colours):
    N = np.random.randint(5, 8)
    positions = (positions + np.zeros(np.r_[N, positions.shape])).reshape(
        (positions.shape[0] * N, 3))
    velocities = (velocities * (1.0 / np.sqrt(N)) + 2 * (np.random.random(
        np.r_[N, velocities.shape]) - 0.5)).reshape(
            (velocities.shape[0] * N, 3))
    colours = (colours * (0.125 + 0.5 * np.random.random(
        np.r_[N, colours.shape]))).reshape((colours.shape[0] * N, 4))

    self._positions = np.r_[self._positions, positions]
    self._colours = np.r_[self._colours, colours]
    self._velocities = np.r_[self._velocities, velocities]
    self._accelerations = np.r_[self._accelerations,
                                np.zeros(positions.shape)]
    self._ages = np.r_[self._ages, np.random.random(positions.shape[0]) *
                       self.particle.lifetime]

</t>
<t tx="karstenw.20230817121939.52">def move(self, dt=0.03125):
    self.apply_forces()
    self.velocities += self.accelerations * dt
    self.positions += self.velocities * dt
    self.ages += dt
    self.colours *= np.array([1.3, 1.3, 1.3, 1.0])


</t>
<t tx="karstenw.20230817121939.53">class Exhaust(Particles):
    @others
</t>
<t tx="karstenw.20230817121939.54">def __init__(self, particle=Particle(
        friction=0.125, lifetime=1.618, elasticity=0.25,
        colour=np.array([255, 255, 153, 255]))):
    self._particle = particle
    self._positions = np.empty((0, 3))
    self._velocities = np.empty((0, 3))
    self._accelerations = np.empty((0, 3))
    self._ages = np.empty((0))
    self._colours = np.empty((0, 4))
    self._visible = True

</t>
<t tx="karstenw.20230817121939.55">def impose_boundary_conditions(self, world):
    self.cull_aged()

    if self.number:
        self.positions[:, self.X] %= world.shape[self.X]
        self.positions[:, self.Y] %= world.shape[self.Y]

        heights = world.map_positions[
            self.positions[:, self.X].astype(int),
            self.positions[:, self.Y].astype(int), self.Z]

        heights = np.where(heights &lt; 0, 0, heights)

        bouncers = np.where(self.positions[:, self.Z] &lt; heights)[0]
        if bouncers.size:
            positions = self.positions[bouncers]

            velocities = self.velocities[bouncers]

            mixing = (
                np.random.random(bouncers.shape)
                * (positions[:, self.Z] &lt;= 0)
            )
            colours = np.clip(world.colours[
                self.positions[bouncers, self.X].astype(int),
                self.positions[bouncers, self.Y].astype(int),
            ] + 64 * mixing[:, np.newaxis], 0, 255)

            self.delete_particles(bouncers)

            return positions, velocities, colours

</t>
<t tx="karstenw.20230817121939.56">def add_particle(self, position, velocity, acceleration, age=0.0,
                 colour=None):
    self.positions = np.r_[self.positions, position[np.newaxis]]
    self.velocities = np.r_[self.velocities, velocity[np.newaxis]]
    self.accelerations = np.r_[self.accelerations,
                               acceleration[np.newaxis]]
    self.ages = np.r_[self.ages, age + np.random.random() *
                      self.particle.lifetime]

    if colour is None:
        self.colours = np.r_[self.colours,
                             (0.5 + np.random.random((1, 4))) *
                             self.particle.colour[np.newaxis]]
    else:
        self.colours = np.r_[self.colours, colour[np.newaxis]]

</t>
<t tx="karstenw.20230817121939.57">def add_particles(self, positions, velocities, accelerations,
                  colours=None):
    N = positions.shape[0]
    self.positions = np.r_[self.positions, positions]
    self.velocities = np.r_[self.velocities, velocities]
    self.accelerations = np.r_[self.accelerations, accelerations]
    self.ages = np.r_[self.ages, np.random.random(N) *
                      self.particle.lifetime]

    if colours is None:
        self.colours = np.r_[self.colours,
                             (0.5 + np.random.random((N, 4))) *
                             self.particle.colour[np.newaxis]]
    else:
        self.colours = np.r_[self.colours, colours]

</t>
<t tx="karstenw.20230817121939.58">def move(self, dt=0.03125):
    self.apply_forces()
    self.velocities += self.accelerations * dt
    self.positions += self.velocities * dt
    self.ages += dt
    self.colours *= np.array([0.96, 0.92, 0.88, 1.0])


</t>
<t tx="karstenw.20230817121939.59">class Stars(Particles):
    """
    TODO:
        * Change  world --&gt; view.
        * map coordinates to ((0, 0); (view.max())
        * make a return, which offsets by player X and Y.
    """

    @others
</t>
<t tx="karstenw.20230817121939.60">def __init__(self, N, view, mean_speed=1.0, min_height=21.0,
             max_height=42.0, particle=Particle(
        gravity=0.0, friction=0.0, lifetime=1.618, elasticity=0.0,
        colour=np.array([204, 102, 204, 255]))):
    self._particle = particle
    self._positions = np.empty((0, 3))
    self._velocities = np.empty((0, 3))
    self._accelerations = np.empty((0, 3))
    self._ages = np.empty((0))
    self._colours = np.empty((0, 4))
    self._min_height = min_height
    self._max_height = max_height
    self._view = view
    self._offset = np.zeros(3)
    self.add_particles(N, mean_speed)
    self._visible = True

</t>
<t tx="karstenw.20230817121939.61">@property
def min_height(self):
    return self._min_height

</t>
<t tx="karstenw.20230817121939.62">@min_height.setter
def min_height(self, val):
    self._min_height = val

</t>
<t tx="karstenw.20230817121939.63">@property
def max_height(self):
    return self._max_height

</t>
<t tx="karstenw.20230817121939.64">@max_height.setter
def max_height(self, val):
    self._max_height = val

</t>
<t tx="karstenw.20230817121939.65">def add_particles(self, N, mean_speed=1.0, colour=None):
    x = np.random.random(N) * self._view[self.X]
    y = np.random.random(N) * self._view[self.Y]
    z = (np.random.random(N) * (self._max_height - self._min_height) +
         self._min_height)

    positions = np.c_[x, y, z]

    velocities = (2.0 * np.random.random((N, 3)) - 1.0) * mean_speed

    self._positions = np.r_[self._positions, positions]
    self.velocities = np.r_[self.velocities, velocities]
    self.accelerations = np.empty((self.number, 3))
    self.ages = np.empty(self.number)

    if colour is None:
        self.colours = np.r_[self.colours,
                             (0.5 + np.random.random((N, 4))) *
                             self.particle.colour[np.newaxis]]
    else:
        self.colours = np.r_[self.colours, colour * np.ones((N, 4))]

</t>
<t tx="karstenw.20230817121939.66">def move(self, velocity, dt=0.03125):
    self._positions += (self.velocities - velocity[np.newaxis]) * dt

</t>
<t tx="karstenw.20230817121939.67">def impose_boundary_conditions(self):
    if self.number:
        self._positions[:, self.X] = (self._positions[:, self.X] %
                                      self._view[self.X])
        self._positions[:, self.Y] = (self._positions[:, self.Y] %
                                      self._view[self.X])
        self._positions[:, self.Z] = ((self._positions[:, self.Z] -
                                       self._min_height) %
                                      (self._max_height - self._min_height)
                                      + self._min_height)

</t>
<t tx="karstenw.20230817121939.68">def impose_boundary_conditions_old(self, world):
    if self.number:
        self._positions[:, self.X] %= world.shape[self.X]
        self._positions[:, self.Y] %= world.shape[self.Y]
        self._positions[:, self.Z] = ((self.positions[:, self.Z] -
                                       self._min_height) %
                                      (self._max_height - self._min_height)
                                      + self._min_height)

</t>
<t tx="karstenw.20230817121939.69">@property
def offset(self):
    return self._offset

</t>
<t tx="karstenw.20230817121939.7">@property
def gravity(self):
    return self._gravity * np.array([0, 0, -1])

@gravity.setter
def gravity(self, val):
    self._gravity = val

</t>
<t tx="karstenw.20230817121939.70">@offset.setter
def offset(self, position):
    self._offset = np.array([position[self.X] - self._view[self.X] * 0.5,
                             position[self.Y] - self._view[self.Y] * 0.5,
                             0.0])

</t>
<t tx="karstenw.20230817121939.71">@property
def positions(self):
    return self._positions + self.offset
</t>
<t tx="karstenw.20230817121939.9">@property
def friction(self):
    return self._friction

@friction.setter
def friction(self, val):
    self._friction = val

</t>
<t tx="karstenw.20230817121941.1">import numpy as np


</t>
<t tx="karstenw.20230817121942.1">class LightSource(object):
    """
    This object has a position (and orientation) for the light source.

    For many applications, using the Camera as a light source is probably what
    is desired.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121942.10">@x.setter
def x(self, val):
    self._position[self.X] = val

</t>
<t tx="karstenw.20230817121942.11">@property
def y(self):
    return self._position[self.Y]

</t>
<t tx="karstenw.20230817121942.12">@y.setter
def y(self, val):
    self._position[self.Y] = val

</t>
<t tx="karstenw.20230817121942.13">@property
def z(self):
    return self._position[self.Z]

</t>
<t tx="karstenw.20230817121942.14">@z.setter
def z(self, val):
    self._position[self.Z] = val

</t>
<t tx="karstenw.20230817121942.15">@property
def u(self):
    return self._orientation[self.U]

</t>
<t tx="karstenw.20230817121942.16">@u.setter
def u(self, val):
    self._orientation[self.U] = val

</t>
<t tx="karstenw.20230817121942.17">@property
def v(self):
    return self._orientation[self.V]

</t>
<t tx="karstenw.20230817121942.18">@v.setter
def v(self, val):
    self._orientation[self.V] = val

</t>
<t tx="karstenw.20230817121942.19">@property
def w(self):
    return self._orientation[self.W]

</t>
<t tx="karstenw.20230817121942.2">def __init__(self,
             position=np.array([6.0, -9.0, 6.0]),
             orientation=np.array([[1.0, 0.0, 0.0],     # u
                                   [0.0, 1.0, 0.0],     # v
                                   [0.0, 0.0, 1.0]]),   # w
             distance=9):
    self._position = position

    self._orientation = orientation

    self._distance = distance

</t>
<t tx="karstenw.20230817121942.20">@w.setter
def w(self, val):
    self._orientation[self.W] = val


</t>
<t tx="karstenw.20230817121942.21">class Shader(object):
    """
    The Shader applies shading to patches, based on the orienation of the
    patches' normals to the light-source.

    Currently, only the position of the light source matters, but there is at
    least a skeleton for implementing light directionality and such at a later
    stage. The standard Camera object can be used as a light source, unless
    a fixed light source is desired.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817121942.22">def __init__(self, light_source=LightSource(),
             colour=np.array([1.4142, 1.4142, 1.4142, 1.0]),
             glare=np.array([51, 51, 51, 255]),
             cutoff_distance=None, linear_distance=None):
    self._light_source = light_source

    self._colour = colour

    self._glare = glare

    if cutoff_distance is None:
        self._cutoff_distance = self.light_source.distance
    else:
        self._cutoff_distance = cutoff_distance

    if linear_distance is None:
        self._linear_distance = self.light_source.distance
    else:
        self._linear_distance = linear_distance

</t>
<t tx="karstenw.20230817121942.23">@property
def light_source(self):
    return self._light_source

</t>
<t tx="karstenw.20230817121942.24">@light_source.setter
def light_source(self, val):
    self._light_source = val

</t>
<t tx="karstenw.20230817121942.25">@property
def colour(self):
    return self._colour

</t>
<t tx="karstenw.20230817121942.26">@colour.setter
def colour(self, val):
    self._colour = val

</t>
<t tx="karstenw.20230817121942.27">@property
def glare(self):
    return self._glare

</t>
<t tx="karstenw.20230817121942.28">@glare.setter
def glare(self, val):
    self._glare = val

</t>
<t tx="karstenw.20230817121942.29">@property
def distance_shading(self):
    return self._distance_shading

</t>
<t tx="karstenw.20230817121942.3">@property
def position(self):
    return self._position

</t>
<t tx="karstenw.20230817121942.30">@distance_shading.setter
def distance_shading(self, val):
    self._distance_shading = val

</t>
<t tx="karstenw.20230817121942.31">@property
def cutoff_distance(self):
    return self._cutoff_distance

</t>
<t tx="karstenw.20230817121942.32">@cutoff_distance.setter
def cutoff_distance(self, val):
    self._cutoff_distance = val

</t>
<t tx="karstenw.20230817121942.33">@property
def linear_distance(self):
    return self._linear_distance

</t>
<t tx="karstenw.20230817121942.34">@linear_distance.setter
def linear_distance(self, val):
    self._linear_distance = val

</t>
<t tx="karstenw.20230817121942.35">def apply_lighting(self, positions, normals, colours, culling=True,
                   scatter=True, fading=True):
    """
    Questions:
        this is done explicitly by reference, changing original colours;
        is that good or annoying?
    """
    deltas = positions - self.light_source.position
    dists = np.sqrt((deltas ** 2).sum(-1))[:, np.newaxis]
    deltas /= dists

    # Apply scatter:
    colours = (colours + self.glare) * self.colour
    if scatter:
        scatter = -(deltas * normals).sum(-1)
        colours *= scatter[:, np.newaxis]

    # Apply distance shading:
    if fading:
        # Gauss:
        # colours *= np.exp(-(dists - self.cutoff_distance) ** 2 /
        #                  (4 * self.cutoff_distance ** 2))

        # Logistic:
        # colours /= 1 + 0.5 * np.exp(dists - 2 * self.cutoff_distance)

        # Linear with cut-off: (LinRange - dists + ConstRange) / LinRange
        colours *= np.fmin(1, np.fmax(0,
                                      (self.linear_distance +
                                       self.cutoff_distance - dists)
                                      / (self.linear_distance)))

    # Renormalise to allowed colour values:
    colours = np.where(colours &gt; 255, 255, colours)
    colours = np.where(colours &lt; 0, 0, colours)
    colours[:, 3] = 255
    if culling:
        colours[np.where(scatter &lt; 0)] = 0

    return colours
</t>
<t tx="karstenw.20230817121942.4">@position.setter
def position(self, val):
    self._position = val

</t>
<t tx="karstenw.20230817121942.5">@property
def orientation(self):
    return self._orientation

</t>
<t tx="karstenw.20230817121942.6">@orientation.setter
def orientation(self, val):
    self._orientation = val

</t>
<t tx="karstenw.20230817121942.7">@property
def distance(self):
    return self._distance

</t>
<t tx="karstenw.20230817121942.8">@distance.setter
def distance(self, val):
    self._distance = val

</t>
<t tx="karstenw.20230817121942.9">@property
def x(self):
    return self._position[self.X]

</t>
<t tx="karstenw.20230817121955.1">import numpy as np

X = U = 0
Y = V = 1
Z = W = 2


</t>
<t tx="karstenw.20230817121955.2">def get_shadows(patches, world):
    """
    Function for getting shadow of object on ground.

    Patch-Z assignment could do with tweaking.
    """

    positions = patches.mean(-2)

    positions[..., Z] = np.where(positions[..., Z] &lt; 0, 0, positions[..., Z])
    xind = patches[..., X].astype(int) % world.shape[X]
    yind = patches[..., Y].astype(int) % world.shape[Y]

    # This needs to be made more accurate
    dists2 = ((patches[..., np.newaxis, : Z] -
               world.patches[xind, yind, :, : Z]) ** 2).sum(-1)
    patches[..., Z] = (world.patches[xind, yind, :, Z]
                       / dists2).sum(-1) / (1 / dists2).sum(-1) - 0.0125
    patches[..., Z] = np.where(patches[..., Z] &lt; 0, 0, patches[..., Z])

    return patches, positions


</t>
<t tx="karstenw.20230817121955.3">def get_small_shadows(patches, world):
    """
    Function for getting shadow of smaller object on ground.

    Simplified Z assignment for small objects
    """

    positions = patches.mean(-2)

    positions[..., Z] = np.where(positions[..., Z] &lt; 0, 0, positions[..., Z])
    xind = patches[..., X].astype(int) % world.shape[X]
    yind = patches[..., Y].astype(int) % world.shape[Y]

    patches[..., Z] = (world.map_positions[xind, yind, Z].mean(-1)
                       )[:, np.newaxis]
    patches[..., Z] = np.where(patches[..., Z] &lt; 0, 0, patches[..., Z])

    return patches, positions
</t>
<t tx="karstenw.20230817122000.1">import datetime as dt

import numpy as np


</t>
<t tx="karstenw.20230817122000.10">@property
def positions(self):
    return (self._scale * self._apply_rotation(self._positions) +
            self.position[np.newaxis, :])

</t>
<t tx="karstenw.20230817122000.11">@property
def engine(self):
    return (self._scale * self._apply_rotation(self._engine) +
            self.position)

</t>
<t tx="karstenw.20230817122000.12">@property
def gun(self):
    return (self._scale * self._apply_rotation(self._gun) + self.position)

</t>
<t tx="karstenw.20230817122000.13">@property
def colours(self):
    return self._colours

</t>
<t tx="karstenw.20230817122000.14">@property
def basecolour(self):
    return self._basecolour

</t>
<t tx="karstenw.20230817122000.15">@basecolour.setter
def basecolour(self, val):
    self._basecolour = val

</t>
<t tx="karstenw.20230817122000.16">@property
def yaw(self):
    return self._yaw

</t>
<t tx="karstenw.20230817122000.17">@yaw.setter
def yaw(self, val):
    self._yaw = val

</t>
<t tx="karstenw.20230817122000.18">@property
def pitch(self):
    return self._pitch

</t>
<t tx="karstenw.20230817122000.19">@pitch.setter
def pitch(self, val):
    self._pitch = val

</t>
<t tx="karstenw.20230817122000.2">class TriD(object):
    """
    Parent class for TriD-objects.
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817122000.20">@property
def roll(self):
    return self._roll

</t>
<t tx="karstenw.20230817122000.21">@roll.setter
def roll(self, val):
    self._roll = val

</t>
<t tx="karstenw.20230817122000.22">@property
def scale(self):
    return self._scale

</t>
<t tx="karstenw.20230817122000.23">@scale.setter
def scale(self, val):
    self._scale = val

</t>
<t tx="karstenw.20230817122000.24">@property
def bounding_box(self):
    return np.c_[self.positions.min(0), self.positions.max(0)].T

</t>
<t tx="karstenw.20230817122000.25">def _colourise(self):
    """
    Not yet fully implemented, but should assign colours...
    """
    # colours = np.zeros([self._patches.shape[0], 3], dtype=int)

    # self._colours = colours + self.basecolour

    pass

</t>
<t tx="karstenw.20230817122000.26">def _calc_positions(self):
    """
    Useful for sorting and the like, maybe.
    """

    self._positions = self._patches.mean(1)

</t>
<t tx="karstenw.20230817122000.27">def _calc_normals(self):
    normals = np.zeros([self._patches.shape[0], 3])

    v0s = self._patches[:, 1] - self._patches[:, 0]
    v1s = self._patches[:, 2] - self._patches[:, 1]

    normals = np.cross(v0s, v1s)
    normals /= np.sqrt((normals ** 2).sum(-1))[:, np.newaxis]

    self._normals = normals

</t>
<t tx="karstenw.20230817122000.28">def _apply_rotation(self, positions):
    y = self.yaw
    p = self.pitch
    r = self.roll

    Rx = np.array([[1, 0, 0],
                   [0, np.cos(p), - np.sin(p)],
                   [0, np.sin(p),   np.cos(p)]])

    Ry = np.array([[ np.cos(r), 0, np.sin(r)],
                   [        0,  1,        0],
                   [-np.sin(r), 0, np.cos(r)]])

    Rz = np.array([[np.cos(y), np.sin(y), 0],
                   [-np.sin(y), np.cos(y), 0],
                   [0, 0, 1]])

    return np.inner(positions, np.dot(Ry, np.dot(Rx, Rz)).T)

</t>
<t tx="karstenw.20230817122000.29">@property
def exploding(self):
    return self._exploding

</t>
<t tx="karstenw.20230817122000.3">def __init__(self, basecolour=np.array([0, 204, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0.0, pitch=0.0, roll=0.0, scale=1.0):
    points = np.array([[1.0, 0.0, -1.0 / np.sqrt(2)],   # 0
                       [-1.0, 0.0, -1.0 / np.sqrt(2)],  # 1
                       [0.0, -1.0, 1.0 / np.sqrt(2)],   # 2
                       [0.0, 1.0, 1.0 / np.sqrt(2)],    # 3
                       ])

    self._patches = np.array([
        [points[1], points[2], points[3]],  # left side
        [points[1], points[0], points[2]],  # back side
        [points[0], points[3], points[2]],  # right side
        [points[0], points[1], points[3]],  # front side
        ])

    self._colours = np.array([[204, 0, 0, 255],
                              [0, 204, 0, 255],
                              [0, 0, 204, 255],
                              [204, 204, 204, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._basecolour = basecolour

    self._position = position

    self._yaw = yaw

    self._pitch = pitch

    self._roll = roll

    self._calc_normals()

    self._calc_positions()

    self._colourise()

    self._scale = scale

    self._exploding = False

    self._exploded = False

</t>
<t tx="karstenw.20230817122000.30">@exploding.setter
def exploding(self, val):
    self._exploding = True if val else False

</t>
<t tx="karstenw.20230817122000.31">@property
def exploded(self):
    return self._exploded

</t>
<t tx="karstenw.20230817122000.32">@exploded.setter
def exploded(self, val):
    self._exploded = True if val else False

</t>
<t tx="karstenw.20230817122000.33">def explode(self):
    if self.exploding:
        self._patches += (
            (np.random.random(self.patches.shape) - 0.5) * 0.05
            + np.random.random(self.patches.shape[0])[
                :, np.newaxis, np.newaxis
            ] * np.ones(self.patches.shape)
            * self.normals[:, np.newaxis, :] * 0.15
        )
    else:
        self.exploding = True


</t>
<t tx="karstenw.20230817122000.34">class FireFighter(TriD):
    """
    Patches for FireFighter.
    """
    @others
</t>
<t tx="karstenw.20230817122000.35">def __init__(self, basecolour=np.array([204, 0, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0, pitch=0, roll=0, scale=1.0):
    super(FireFighter, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([
        # Bottom:
        [0, 0.5, 0],         # 0
        [-0.5, -.25, 0],     # 1
        [0.5, -.25, 0],      # 2
        # Middle:
        [0.15, 0.7, 0.17],   # 3
        [-0.15, 0.7, 0.17],  # 4
        [-0.7, 0.0, 0.1],    # 5
        [0.0, -0.5, 0.1],    # 6
        [0.7, 0.0, 0.1],     # 7
        # Top:
        [0.0, 0.2, 0.3],     # 8
        [0.0, 0.0, 0.2],     # 9
        ])

    es = 0.17
    offset = np.array([0.0, 0.0, 0.0])
    points += offset

    self._patches = np.array([
        # Bottom:
        [points[1], points[0], points[0] * es],                       # FP
        [points[1], points[0] * es, points[1] * es],                  # MP
        [points[1], points[1] * es, points[(1, 2), :].mean(0)],       # BP
        [points[2], points[0] * es, points[0]],                       # FS
        [points[2], points[2] * es, points[0] * es],                  # MS
        [points[2], points[(1, 2), :].mean(0), points[2] * es],       # BS
        [points[(1, 2), :].mean(0), points[1] * es, points[2] * es],  # B
        # Engine:
        [points[0] * es, points[2] * es, points[1] * es],
        # Bow:
        [points[0], points[4], points[3]],                  # Front
        [points[0], points[(0, 1), :].mean(0), points[4]],  # F Port
        [points[0], points[3], points[(0, 2), :].mean(0)],  # F Starboard
        # Bottom Stern:
        [points[6], points[1], points[2]],
        # Bottom Port:
        [points[1], points[5], points[(0, 1), :].mean(0)],
        # Bottom Starboard:
        [points[7], points[2], points[(0, 2), :].mean(0)],
        # Cockpit:
        [points[3], points[4], points[8]],                  # Glass
        [points[4], points[(0, 1), :].mean(0), points[8]],  # F Port
        [points[8], points[(0, 2), :].mean(0), points[3]],  # F Starboard
        [points[8], points[(0, 1), :].mean(0), points[9]],  # B Port
        [points[9], points[(0, 2), :].mean(0), points[8]],  # B Starboard
        # Stern:
        [points[1], points[6], points[9]],  # Port
        [points[6], points[2], points[9]],  # Starboard
        # Wings:
        [points[5], points[9], points[(0, 1), :].mean(0)],  # P Front
        [points[5], points[1], points[9]],                  # P Back
        [points[7], points[(0, 2), :].mean(0), points[9]],  # S Front
        [points[7], points[9], points[2]],                  # S Back
        ])

    points[:, 1] *= np.sqrt(3) / 2.0

    self._colours = np.array([[51, 51, 102, 255],   # Bottom:
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [204, 102, 0, 255],   # Engine
                              [0, 0, 51, 255],    # Bow:
                              [0, 0, 102, 255],
                              [0, 0, 102, 255],
                              [0, 0, 102, 255],     # Stern
                              [51, 0, 51, 255],     # Bottom Port
                              [0, 51, 51, 255],     # Bottom Starboard
                              [51, 153, 153, 255],  # Cockpit:
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],  # Stern:
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],  # Wings:
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],
                              [153, 0, 0, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._calc_normals()

    self._calc_positions()

    self._colourise()

    self._engine = np.array([0.0, 0.0, 0.0])

    self._gun = self._patches[8].mean(0)


</t>
<t tx="karstenw.20230817122000.36">class FireFighterStripes(TriD):
    """
    Patches for FireFighter.
    """
    @others
</t>
<t tx="karstenw.20230817122000.37">def __init__(self, basecolour=np.array([204, 0, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0, pitch=0, roll=0, scale=1.0):
    super(FireFighterStripes, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([
        # Bottom:
        [0, 0.5, 0],         # 0
        [-0.5, -.25, 0],     # 1
        [0.5, -.25, 0],      # 2
        # Middle:
        [0.17, 0.7, 0.17],   # 3
        [-0.17, 0.7, 0.17],  # 4
        [-0.7, 0.0, 0.1],    # 5
        [0.0, -0.5, 0.1],    # 6
        [0.7, 0.0, 0.1],     # 7
        # Top
        [0.0, 0.2, 0.3],     # 8
        [0.0, 0.0, 0.2],     # 9
        # Wing details:
        [-0.5875, 0.03125, 0.075],  # 10
        [-0.65, -0.0625, 0.075],    # 11
        [0.65, -0.0625, 0.075],     # 12
        [0.5875, 0.03125, 0.075],   # 13
        ])

    es = 0.17

    self._patches = np.array([
        # Bottom:
        [points[1], points[0], points[0] * es],                       # FP
        [points[1], points[0] * es, points[1] * es],                  # MP
        [points[1], points[1] * es, points[(1, 2), :].mean(0)],       # BP
        [points[2], points[0] * es, points[0]],                       # FS
        [points[2], points[2] * es, points[0] * es],                  # MS
        [points[2], points[(1, 2), :].mean(0), points[2] * es],       # BS
        [points[(1, 2), :].mean(0), points[1] * es, points[2] * es],  # B
        # Engine:
        [points[0] * es, points[2] * es, points[1] * es],
        # Bow:
        [points[0], points[4], points[3]],                  # Front
        [points[0], points[(0, 1), :].mean(0), points[4]],  # F Port
        [points[0], points[3], points[(0, 2), :].mean(0)],  # F Starboard
        # Bottom Stern:
        [points[6], points[1], points[2]],
        # Bottom Port:
        [points[1], points[5], points[(0, 1), :].mean(0)],
        # Bottom Starboard:
        [points[7], points[2], points[(0, 2), :].mean(0)],
        # Cockpit:
        [points[3], points[4], points[8]],                  # Glass
        [points[4], points[(0, 1), :].mean(0), points[8]],  # F Port
        [points[8], points[(0, 2), :].mean(0), points[3]],  # F Starboard
        [points[8], points[(0, 1), :].mean(0), points[9]],  # B Port
        [points[9], points[(0, 2), :].mean(0), points[8]],  # B Starboard
        # Stern:
        [points[1], points[6], points[9]],  # Port
        [points[6], points[2], points[9]],  # Starboard
        # Wings:
        [points[10], points[9], points[(0, 1), :].mean(0)],  # P Front
        [points[11], points[1], points[9]],                  # P Back
        [points[13], points[(0, 2), :].mean(0), points[9]],  # S Front
        [points[12], points[9], points[2]],                  # S Back
        [points[11], points[10], points[5]],                 # P Light
        [points[13], points[12], points[7]],                 # S Light
        [points[11], points[9], points[10]],                 # P Stripe
        [points[13], points[9], points[12]],                 # S Stripe
        ])

    points[:, 1] *= np.sqrt(3) / 2.0

    self._colours = np.array([[51, 51, 102, 255],   # Bottom:
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [51, 51, 102, 255],
                              [204, 102, 0, 255],   # Engine
                              [0, 0, 102, 255],     # Stern:
                              [0, 0, 102, 255],
                              [0, 0, 102, 255],
                              [0, 0, 102, 255],     # Bow
                              [51, 0, 102, 255],    # Bottom Port
                              [0, 51, 102, 255],    # Bottom Starboard
                              [51, 153, 153, 255],  # Cockpit:
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],  # Stern:
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],  # Wings:
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],
                              [102, 0, 0, 255],
                              [204, 0, 0, 255],
                              [0, 204, 0, 255],
                              [204, 204, 0, 255],
                              [204, 204, 0, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._calc_normals()

    self._calc_positions()

    self._colourise()

    self._engine = np.array([0.0, 0.0, 0.0])

    self._gun = self.patches[8].mean(0)


</t>
<t tx="karstenw.20230817122000.38">class Pika(TriD):
    """
    Patches for Pika.
    """
    @others
</t>
<t tx="karstenw.20230817122000.39">def __init__(self, basecolour=np.array([204, 204, 204, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0, pitch=0, roll=0, scale=1.0):
    super(Pika, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([[0.0, 0.35, 0.05],   # 0
                       [-0.1, 0.1, 0.05],   # 1
                       [-0.2, 0.1, 0.05],   # 2
                       [-0.6, 0.0, 0.0],    # 3
                       [-0.7, -0.1, 0.0],   # 4
                       [0.0, -0.2, 0.05],   # 5
                       [-0.1, -0.65, 0.0],  # 6
                       [0.0, -0.75, 0.05],  # 7
                       [0.1, -0.65, 0.0],   # 8
                       [0.7, -0.1, 0.0],    # 9
                       [0.6, 0.0, 0.0],     # 10
                       [0.2, 0.1, 0.05],    # 11
                       [0.1, 0.1, 0.05],    # 12
                       [0.0, 0.2, 0.15],    # 13
                       [0.0, 0.0, 0.0],     # 14
                       ])

    self._patches = np.array([
        # Body:
        [points[0], points[1], points[13]],     # 0: head top left
        [points[12], points[0], points[13]],    # 1: head top right
        [points[1], points[5], points[13]],     # 2: back top left
        [points[5], points[12], points[13]],    # 3: back top right
        [points[1], points[0], points[14]],     # 4: head bottom left
        [points[0], points[12], points[14]],    # 5: head bottom right
        [points[5], points[1], points[14]],     # 6: back bottom left
        [points[12], points[5], points[14]],    # 7: back bottom right
        # Tail:
        [points[5], points[6], points[7]],      # 8: top left
        [points[8], points[5], points[7]],      # 9: top right
        [points[6], points[5], points[7]],      # 10: bottom left
        [points[5], points[8], points[7]],      # 11: bottom right
        # Left wing
        [points[1], points[2], points[5]],      # 12: inner top
        [points[2], points[3], points[5]],      # 13: middle top
        [points[3], points[4], points[5]],      # 14: tip top
        [points[2], points[1], points[5]],      # 15: inner bottom
        [points[3], points[2], points[5]],      # 16: middle bottom
        [points[4], points[3], points[5]],      # 17: tip bottom
        # Right wing
        [points[11], points[12], points[5]],    # 18: inner top
        [points[10], points[11], points[5]],    # 19: middle top
        [points[9], points[10], points[5]],     # 20: tip top
        [points[12], points[11], points[5]],    # 21: inner bottom
        [points[11], points[10], points[5]],    # 22: middle bottom
        [points[10], points[9], points[5]],     # 23: tip bottom
        ])

    self._colours = np.array([
        # Body:
        [0, 0, 0, 255],
        [0, 0, 0, 255],
        [0, 0, 26, 255],
        [0, 0, 26, 255],
        [204, 204, 204, 255],
        [204, 204, 204, 255],
        [0, 0, 0, 255],
        [0, 0, 0, 255],
        # Tail:
        [0, 26, 0, 255],
        [0, 26, 0, 255],
        [0, 13, 0, 255],
        [0, 13, 0, 255],
        # Left wing:
        [204, 204, 204, 255],
        [0, 13, 0, 255],
        [204, 204, 204, 255],
        [204, 204, 204, 255],
        [0, 0, 0, 255],
        [204, 204, 204, 255],
        # Right wing:
        [204, 204, 204, 255],
        [0, 13, 0, 255],
        [204, 204, 204, 255],
        [204, 204, 204, 255],
        [0, 0, 0, 255],
        [204, 204, 204, 255],
        ]) - 26

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._calc_normals()

    self._calc_positions()

    self._colourise()

    self._engine = np.array([0.0, 0.0, 0.0])

    self._gun = points[0]


</t>
<t tx="karstenw.20230817122000.4">@property
def orientation(self):
    return self._apply_rotation(self._orientation)

</t>
<t tx="karstenw.20230817122000.40">class Lander(TriD):
    """
    Patches for Lander.
    """
    @others
</t>
<t tx="karstenw.20230817122000.41">def __init__(self, basecolour=np.array([0, 204, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0, pitch=0, roll=0, scale=1.0):
    super(Lander, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([[0.5, 1.0, 0.0],     # 0
                       [-0.5, 1.0, 0.0],    # 1
                       [-1.2, -0.1, 0.2],   # 2
                       [0.0, -1.0, 0.0],    # 3
                       [1.2, -0.1, 0.2],    # 4
                       [0.0, -0.4, 0.8],    # 5
                       [0.10, 0.2, 0.0],    # 6
                       [-.10, 0.2, 0.0],    # 7
                       [0.0, -0.2, 0.0],    # 8
                       ])

    self._patches = np.array([
        [points[0], points[1], points[5]],  # 0: front
        [points[1], points[2], points[5]],  # 1: front left
        [points[2], points[3], points[5]],  # 2: back left
        [points[3], points[4], points[5]],  # 3: back right
        [points[4], points[0], points[5]],  # 4: front right
        [(points[1] + points[0]) * 0.5,     # 5: bottom front centre
         points[6], points[7]],
        [(points[1] + points[0]) * 0.5,     # 6: bottom front left
         points[7], points[1]],
        [(points[1] + points[0]) * 0.5,     # 7: bottom front right
         points[0], points[6]],
        [points[1], points[7], points[3]],  # 8: bottom left front
        [points[7], points[8], points[3]],  # 9: bottom left back
        [points[6], points[0], points[3]],  # A: bottom right front
        [points[8], points[6], points[3]],  # B: bottom right back
        [points[3], points[2], points[1]],  # C: bottom left wing
        [points[3], points[0], points[4]],  # D: bottom right wing
        [points[8], points[7], points[6]],  # E: engine A
        ])

    self._colours = np.array([[0, 204, 0, 255],
                              [0, 153, 0, 255],
                              [0, 204, 0, 255],
                              [0, 204, 0, 255],
                              [0, 153, 0, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 153, 255],
                              [0, 0, 204, 255],
                              [0, 0, 204, 255],
                              [204, 204, 0, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._calc_normals()

    self._calc_positions()

    self._colourise()

    self._engine = np.array([0.0, 0.0, 0.0])

    self._gun = np.array([0.0, 1.0, 0.0])


</t>
<t tx="karstenw.20230817122000.42">class House(TriD):
    """
    Patches for House with nicer shading and sorting properties than
    SimpleHouse, though twice as complex...
    """

    @others
</t>
<t tx="karstenw.20230817122000.43">def __init__(self, basecolour=np.array([0, 204, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0.0, pitch=0.0, roll=0.0, scale=1.0):
    super(House, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([[0.7, 1.2, 0.0],       # 0
                       [-0.7, 1.2, 0.0],      # 1
                       [-0.7, -1.2, 0.0],     # 2
                       [0.7, -1.2, 0.0],      # 3
                       [0.7, 1.2, 0.7],      # 4
                       [-0.7, 1.2, 0.7],     # 5
                       [-0.7, -1.2, 0.7],    # 6
                       [0.7, -1.2, 0.7],     # 7
                       [0.0, 1.2, 1.0],       # 8
                       [0.0, -1.2, 1.0],      # 9
                       ])

    self._patches = np.array([
        # North side:
        [points[0], points[1], points[(0, 1, 4, 5), :].mean(0)],  # bottom
        [points[5], points[4], points[(0, 1, 4, 5), :].mean(0)],  # middle
        [points[1], points[5], points[(0, 1, 4, 5), :].mean(0)],  # west
        [points[4], points[0], points[(0, 1, 4, 5), :].mean(0)],  # east
        [points[4], points[5], points[8]],                        # top
        # South side:
        [points[2], points[3], points[(2, 3, 6, 7), :].mean(0)],  # lower
        [points[7], points[6], points[(2, 3, 6, 7), :].mean(0)],  # middle
        [points[6], points[2], points[(2, 3, 6, 7), :].mean(0)],  # west
        [points[3], points[7], points[(2, 3, 6, 7), :].mean(0)],  # east
        [points[6], points[7], points[9]],                        # top
        # West side:
        [points[1], points[2], points[(1, 2, 5, 6), :].mean(0)],  # bottom
        [points[6], points[5], points[(1, 2, 5, 6), :].mean(0)],  # top
        [points[5], points[1], points[(1, 2, 5, 6), :].mean(0)],  # north
        [points[2], points[6], points[(1, 2, 5, 6), :].mean(0)],  # south
        # East side:
        [points[3], points[0], points[(0, 3, 4, 7), :].mean(0)],  # bottom
        [points[4], points[7], points[(0, 3, 4, 7), :].mean(0)],  # top
        [points[0], points[4], points[(0, 3, 4, 7), :].mean(0)],  # north
        [points[7], points[3], points[(0, 3, 4, 7), :].mean(0)],  # south
        # West roof:
        [points[5], points[6], points[(5, 6, 8, 9), :].mean(0)],  # bottom
        [points[9], points[8], points[(5, 6, 8, 9), :].mean(0)],  # top
        [points[8], points[5], points[(5, 6, 8, 9), :].mean(0)],  # north
        [points[6], points[9], points[(5, 6, 8, 9), :].mean(0)],  # south
        # East roof:
        [points[7], points[4], points[(4, 7, 8, 9), :].mean(0)],  # bottom
        [points[8], points[9], points[(4, 7, 8, 9), :].mean(0)],  # top
        [points[4], points[8], points[(4, 7, 8, 9), :].mean(0)],  # north
        [points[9], points[7], points[(4, 7, 8, 9), :].mean(0)],  # south
        ])

    self._colours = np.array([[153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])
    self._calc_normals()

    self._calc_positions()

    self._colourise()


</t>
<t tx="karstenw.20230817122000.44">class SimpleHouse(TriD):
    """
    Patches for SimpleHouse with reduced triangle count. Probably a tiny bit
    faster to render than House.
    """

    @others
</t>
<t tx="karstenw.20230817122000.45">def __init__(self, basecolour=np.array([0, 204, 0, 255]),
             position=np.array([0.0, 0.0, 0.0]),
             yaw=0.0, pitch=0.0, roll=0.0, scale=1.0):
    super(SimpleHouse, self).__init__(
        basecolour, position, yaw, pitch, roll, scale,
    )

    points = np.array([[0.7, 1.2, 0.0],       # 0
                       [-0.7, 1.2, 0.0],      # 1
                       [-0.7, -1.2, 0.0],     # 2
                       [0.7, -1.2, 0.0],      # 3
                       [0.7, 1.2, 0.7],      # 4
                       [-0.7, 1.2, 0.7],     # 5
                       [-0.7, -1.2, 0.7],    # 6
                       [0.7, -1.2, 0.7],     # 7
                       [0.0, 1.2, 1.0],       # 8
                       [0.0, -1.2, 1.0],      # 9
                       ])

    self._patches = np.array([
        [points[0], points[1], points[4]],  # N bottom
        [points[4], points[1], points[5]],  # N mid
        [points[4], points[5], points[8]],  # N top
        [points[2], points[3], points[6]],  # S bottom
        [points[6], points[3], points[7]],  # S mid
        [points[6], points[7], points[9]],  # S top
        [points[1], points[2], points[5]],  # W bottom
        [points[5], points[2], points[6]],  # W top
        [points[3], points[0], points[7]],  # E bottom
        [points[7], points[0], points[4]],  # E top
        [points[5], points[6], points[9]],  # W roof bottom
        [points[9], points[8], points[5]],  # W roof top
        [points[7], points[4], points[9]],  # E roof bottom
        [points[9], points[4], points[8]],  # E roof top
        ])

    self._colours = np.array([[153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [153, 153, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [102, 102, 102, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              [0, 102, 0, 255],
                              ])

    self._orientation = np.array([[1.0, 0.0, 0.0],  # U
                                  [0.0, 1.0, 0.0],  # V
                                  [0.0, 0.0, 1.0]   # W
                                  ])

    self._calc_normals()

    self._calc_positions()

    self._colourise()


</t>
<t tx="karstenw.20230817122000.46">class TriDGroup(object):
    """
    What do I want from a TriDGroup?

    * To add models.
    * To delete models.
    * To get patches/colours/patch positions for a single model
    * To get all patches/colours/pach positions.
    * To get all objects centre positions
    """

    X = U = 0
    Y = V = 1
    Z = W = 2

    @others
</t>
<t tx="karstenw.20230817122000.47">def __init__(self, model=House(), timeout=3):
    self._model = model
    N = self._model.patches.shape[0]
    self._positions = np.empty((0, 3))
    self._patches = np.empty((0, N, 3, 3))
    self._patch_positions = np.empty((0, N, 3))
    self._normals = np.empty((0, N, 3))
    self._colours = np.empty((0, N, 4))
    self._bboxes = np.empty((0, 2, 3))
    self._yaws = np.empty((0))
    self._pitchs = np.empty((0))
    self._rolls = np.empty((0))
    self._exploding = np.empty((0), dtype=object)
    self._timeout = dt.timedelta(seconds=timeout)

</t>
<t tx="karstenw.20230817122000.48">@property
def model(self):
    return self._model

</t>
<t tx="karstenw.20230817122000.49">@model.setter
def model(self, val):
    self._model = val

</t>
<t tx="karstenw.20230817122000.5">@property
def centre_of_mass(self):
    return self.patches.mean(0).mean(0)

</t>
<t tx="karstenw.20230817122000.50">@property
def number(self):
    return self.positions.shape[0]

</t>
<t tx="karstenw.20230817122000.51">@property
def positions(self):
    return self._positions

</t>
<t tx="karstenw.20230817122000.52">def patches(self, indices):
    N = self._patches.shape[1] * indices.size
    return self._patches[indices].reshape((N, 3, 3))

</t>
<t tx="karstenw.20230817122000.53">def patch_positions(self, indices):
    N = self._patch_positions.shape[1] * indices.size
    return self._patch_positions[indices].reshape((N, 3))

</t>
<t tx="karstenw.20230817122000.54">def normals(self, indices):
    N = self._normals.shape[1] * indices.size
    return self._normals[indices].reshape((N, 3))

</t>
<t tx="karstenw.20230817122000.55">def colours(self, indices):
    N = self._colours.shape[1] * indices.size
    return self._colours[indices].reshape((N, 4))

</t>
<t tx="karstenw.20230817122000.56">def bboxes(self, indices):
    return self._bboxes[indices]

</t>
<t tx="karstenw.20230817122000.57">def add_object(self, position, yaw=0.0, pitch=0.0, roll=0.0):
    self._positions = np.r_[self._positions, position[np.newaxis]]
    self._yaws = np.r_[self._yaws, yaw]
    self._pitchs = np.r_[self._pitchs, pitch]
    self._rolls = np.r_[self._rolls, roll]

    self.model.position = position
    self.model.yaw = yaw
    self.model.pitch = pitch
    self.model.roll = roll

    self._patches = np.r_[self._patches, self.model.patches[np.newaxis]]
    self._patch_positions = np.r_[self._patch_positions,
                                  self.model.positions[np.newaxis]]
    self._normals = np.r_[self._normals, self.model.normals[np.newaxis]]
    self._colours = np.r_[self._colours, self.model.colours[np.newaxis]]
    self._bboxes = np.r_[self._bboxes, self.model.bounding_box[np.newaxis]]
    self._exploding = np.r_[self._exploding, [False]]

</t>
<t tx="karstenw.20230817122000.58">def delete_object(self, n):
    indices = np.arange(self._positions.shape[0]) != n
    self._positions = self._positions[indices]
    self._yaws = self._yaws[indices]
    self._pitchs = self._pitchs[indices]
    self._rolls = self._rolls[indices]
    self._patches = self._patches[indices]
    self._patch_positions = self._patch_positions[indices]
    self._normals = self._normals[indices]
    self._colours = self._colours[indices]
    self._bboxes = self._bboxes[indices]
    self._exploding = self._exploding[indices]

</t>
<t tx="karstenw.20230817122000.59">@property
def exploding(self):
    return self._exploding

</t>
<t tx="karstenw.20230817122000.6">@property
def position(self):
    return self._position

</t>
<t tx="karstenw.20230817122000.60">@property
def timeout(self):
    return self._timeout

</t>
<t tx="karstenw.20230817122000.61">def explode_object(self, n):
    if self._exploding[n]:
        self._patches[n] += (
            (np.random.random(self._patches[n].shape) - 0.5) * 0.15
            + np.random.random(self._patches[n].shape[0])[
                :, np.newaxis, np.newaxis
            ] * np.ones(self._patches[n].shape)
            * self._normals[n, :, np.newaxis, :] * 0.05
        )
    else:
        self._exploding[n] = dt.datetime.now()
</t>
<t tx="karstenw.20230817122000.7">@position.setter
def position(self, val):
    self._position = val

</t>
<t tx="karstenw.20230817122000.8">@property
def patches(self):
    return (self._scale * self._apply_rotation(self._patches) +
            self.position[np.newaxis, np.newaxis, :])

</t>
<t tx="karstenw.20230817122000.9">@property
def normals(self):
    return self._apply_rotation(self._normals)

</t>
<t tx="karstenw.20230817183046.1">@language python
@tabwidth -4
@others
if __name__ == "__main__":
    sys.exit(main())
</t>
<t tx="karstenw.20230817183101.1">#! /usr/bin/env python

from __future__ import print_function

import sys
import pygame
import pygame.locals as l
import src.menu as m
import src.game as g


KEYBOARD = {l.K_UP: 'up', l.K_k: 'up', l.K_w: 'up',
            l.K_DOWN: 'down', l.K_j: 'down', l.K_s: 'down',
            l.K_LEFT: 'left', l.K_h: 'left', l.K_a: 'left',
            l.K_RIGHT: 'right', l.K_l: 'right', l.K_d: 'right',
            l.K_RETURN: 'start', l.K_SPACE: 'start',
            l.K_ESCAPE: 'quit', l.K_F1: 'help'}

FONTS = True
if not pygame.font:
    print( "Warning: no fonts detected; fonts disabled." )
    FONTS = False

if not pygame.mixer:
    print( "Warning: no sound detected; sound disabled." )
    MIXER = None
else:
    pygame.mixer.init()
    MIXER = pygame.mixer


</t>
<t tx="karstenw.20230817183101.2">def main():
    pygame.init()


    fps_clock = pygame.time.Clock()
    fps = 23.8
    window = pygame.display.set_mode((640, 480), pygame.DOUBLEBUF)

    mode = "menu"
    menu = m.Menu('config/menu.conf', 'config/user.conf',
                  'config/default.conf', MIXER)

    while(mode):

        while(mode == "menu"):

            if menu.resolution != window.get_size():

                window = pygame.display.set_mode(menu.resolution,
                                                 pygame.DOUBLEBUF)

            m.draw_menu(menu, window)
            pygame.display.flip()
            fps_clock.tick(fps)

            mode = menu.menu_navigation()

        if mode == "game":
            try:
                print( "loading map: {0}".format(menu.config["map"]) )
                game = g.Game(menu.config, 'assets/maps/{0}.npy'.format(
                    menu.config["map"]), menu.setup["font"],
                    menu.setup["fontsize"], fps)
                pygame.event.set_grab(True)
                pygame.mouse.set_visible(False)
                pygame.mouse.get_rel()
            except IOError:
                print( "no such map: {0}; using Legacy".format( 
                    menu.config["map"]) )
                game = g.Game(menu.config, 'assets/maps/legacy.npy',
                              menu.setup["font"], menu.setup["fontsize"], fps)
                pygame.event.set_grab(True)
                pygame.mouse.set_visible(False)
                pygame.mouse.get_rel()

        while(mode == "game"):
            mode = game.do_step(window)
            pygame.display.flip()
            fps_clock.tick(fps)

        while(mode == "hiscore"):
            print( "high-score list is not implemented. returning to menu ..." )
            mode = "menu"

        while(mode == "gallery"):
            print( "gallery is not implemented. returning to menu ..." )
            mode = "menu"

        while(mode == "credits"):
            print( "credits is not implemented. returning to menu ..." )
            mode = "menu"

        while(mode == "quit"):
            print( "quitting game ..." )
            pygame.quit()
            mode = False

</t>
<t tx="karstenw.20230817194702.1">print( "initialising world map ... ", end=" " )
self.world = e.mapper.Map(world)
print( "DONE" )
</t>
<t tx="karstenw.20230817194741.1">print( "loading fonts ... ", end= " ")
fontsize = int( fontsize * config["resolution"][0] / 320 )
self._font = pygame.font.Font(font, fontsize)
print( "DONE" )
</t>
<t tx="karstenw.20230817194824.1">print( "loading game objects ... ", end=" ")
if not self._config[" "]:
    self.player = e.mobs.Player(e.triDobjects.FireFighter(scale=2.0))
    # self.player = e.mobs.Player(e.triDobjects.Pika(scale=3.0))
else:
    self.player = e.mobs.Player(e.triDobjects.Lander(scale=1.0))

self.player.position = (np.array([64.0, 64.0, 5.0]))
print( "DONE" )
</t>
<t tx="karstenw.20230817194901.1">print( "seting up camera ... ", end=" ")
self.camera = e.camera.Camera(screen=e.camera.Screen(
    resolution=config["resolution"]))

if config["camera"] == "fixed":
    self.update_camera = self.update_fixed_camera
    D = self._view[self.Y]
    h = (self.camera.screen.extent[self.Y] * 0.5 -
         self.camera.screen.position[self.Z])
    d = self.camera.distance
elif config["camera"] == "rear":
    self.update_camera = self.update_rear_camera
    self.config["view"] = (self._view[0], self._view[0])
    D = self._view[self.Y] * (1 + np.sqrt(2)) * 0.5
    h = (self.camera.screen.extent[self.Y] * 0.5 -
         self.camera.screen.position[self.Z])
    d = self.camera.distance
else:
    # copy of fixed - should never be called
    self.update_camera = self.update_fixed_camera
    D = self._view[self.Y]
    h = (self.camera.screen.extent[self.Y] * 0.5 -
         self.camera.screen.position[self.Z])
    d = self.camera.distance

self._culling_height = np.ceil(
        (h * (D / d + 1.0)
        + np.ceil( self.world.patch_positions[:, :, self.Z].max())))
self._star_field_height = self._culling_height

self.light_source = e.shader.LightSource()

self.shader = e.shader.Shader(self.light_source,
                              cutoff_distance=self._view[self.Y] * 0.5
                              + self.camera.distance,
                              linear_distance=self._view[self.Y] *
                              0.75)

self.update_camera()
print( "DONE" )
</t>
<t tx="karstenw.20230817195031.1">print( "initialising game objects ... ", end=" " )
self._populate_world()
self.shots = e.particles.Shots()
self.shrapnel = e.particles.Shrapnel()
self.exhaust = e.particles.Exhaust()
self.star_field = e.particles.Stars(int(0.25 * self._view[0] ** 2),
                                    self._view + self.camera.distance
                                    - 0.5,
                                    min_height=self._star_field_height)
print( "DONE" )
</t>
</tnodes>
</leo_file>
